### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-base#10]
I've got a few suggestions for the Publish logo, let me know what you think @ljkart 
## 1

![](https://github.com/abstractfactory/publish/wiki/images/icon1.png) 
## 2

![](https://github.com/abstractfactory/publish/wiki/images/icon2.png) 
## 3

![](https://github.com/abstractfactory/publish/wiki/images/icon3.png)
## 4

![](https://github.com/abstractfactory/publish/wiki/images/icon4.png) 
## 5

![](https://github.com/abstractfactory/publish/wiki/images/icon5.jpg) 
## 6

![](https://github.com/abstractfactory/publish/wiki/images/icon6.png) 
## 7

![](https://github.com/abstractfactory/publish/wiki/images/icon7.png) 
## 8

![](https://github.com/abstractfactory/publish/wiki/images/icon8.jpg) 
## 9

![](https://github.com/abstractfactory/publish/wiki/images/icon9.jpg)

**Comment by ljkart** [comment]
the black looks better. the first one.

**Comment by madoodia** [comment]
Why A Funnel??

**Comment by mottosso** [comment]
@madoodia That is a good question. :) I say, throw in any suggestions you have, and we'll decide once all cards are on the table!

My intent was, that a funnel is a fan-in for many diverse sources (artists), with a single common output (published packages). Basically; mess in, tidy out. A filter of sorts would work well too, or if you have any other suggestions.

**Comment by madoodia** [comment]
But we don't have single output,we orgenized them, we adjust them according our need.
you know?
i mean we get an artist's work and print a standard hologram on it and standardize it, no?

**Comment by mottosso** [comment]
There is no organising of files; that is optional and outside the scope of Publish.

See here: [Scope](https://github.com/abstractfactory/publish/wiki/scope)

But rather, Publish filters outgoing data to ensure that it conforms to a pre-defined standard. Filters are called [validators](https://github.com/abstractfactory/publish/wiki/validation).

For example, on the next Spiderman film, all geometry of characters must not be above 3 meters in height, and 1 meters in width. A filter/validator would ensure that, before the geometry is allowed to be published.

Feel free to post suggestions!

**Comment by BigRoy** [comment]
I like the idea of a funnel and especially like icon4.png because it pops out with the added green bar. Also I like the rounded edges on it, yet the top part could get some more detail. Maybe just a hole?

**Comment by rajivfx** [comment]
logo color should be green 
I think icon7.png

Publish is the goal of artist who make tons of version , corrections and lots of retakes.
green is refreshing color and give happy feel to artist.

and what is the color of main GUI (white, Black or other)..?
Green colour should fit in all.
The icon7.png design is perfect

what you guys think..?

**Comment by mottosso** [comment]
We've been having one of the above logos on trial for the past few weeks, and I think it's worked out rather nicely. However, I've mocked up an alternative and would like your opinion on whether it is a step forwards, or backwards.

![logo_macaw_small](https://cloud.githubusercontent.com/assets/2152766/4263236/f2b4e8f8-3bd7-11e4-9bc1-f4c90c29abfc.png) ![logo_small](https://cloud.githubusercontent.com/assets/2152766/4263237/f8df52ae-3bd7-11e4-94dd-1af326d311a6.png)

Current one in action here: https://github.com/abstractfactory/pyblish
Suggested one here: http://pyblish.com/

**Comment by mottosso** [comment]
Feel free to discuss any other logotype suggestions in the [usergroup](https://groups.google.com/forum/#!forum/pyblish)
