### ISSUE TITLE
Renaming plugin class doesn't update

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-base#106]
- Renaming a plugin class in Maya, doesn't change the logging.
- Breaking that renamed plugin, give an error in the log.
- Renaming the plugin class back to the original, and the error persists.

**Comment by mottosso** [comment]
Some more info on this.

Running the [included example](https://github.com/abstractfactory/pyblish-maya/tree/master/examples/example1) of Pyblish Maya and publishing with [`ExtractModelAsObj`](https://github.com/abstractfactory/pyblish-maya/blob/master/pyblish_maya/plugins/extract_as_obj.py) works well. Then renaming it to `ExtractModelAsObj2` produces _duplicate_ plug-ins; one by the original name, and one using the old.

This occurs in both logging and the Pyblish QML GUI.

Hunting this down now.

**Comment by mottosso** [comment]
This looks to be due to a particularity in how the Python import mechanism works and was difficult to test and thus difficult to fix.

Marking this as a minor inconvenience for now.

**Comment by mottosso** [comment]
Encountered a solution to this on the interwebs just now by chance.

Apparently, the Python import mechanism implicitly "merges" a module with another is another one of the same name is already in `sys.modules`, which is the case here as the plug-in class changed, but the file did not, resulting in two classes.

The solution was simple (though hacky). Remove it from `sys.modules` before importing it again.
