### ISSUE TITLE
"Abort"

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-base#121]
In case of plug-ins taking a long time and/or being triggered by mistake, we shouldn't force the user to kill the host.

By running plug-ins in a separate thread, we can provide better status information along with the option to kill just the thread, without requiring shut-down of the host.

Provide an "Abort" function, either via a GUI or by leaving Maya responsive during a publish (dangerous) allowing users to type it in by hand.

**Comment by BigRoy** [comment]
Maya does allow to show a progress bar and capture whether the user has requested it to 'quit' (I think it takes the escape button as quiting. Though you would have to implement actually aborting it yourself. We could add a `self.is_aborted` attribute on all plug-ins that gets set to True when the user has requested to stop. Then with very slow/intensive plug-ins one can easily implement the _Abort_ in for example a _for loop_. Otherwise Pyblish manages itself in-between each plug-in.

``` python
def process_instance(self, instance):
    for node in instance:
        heavy_computation(node)
        if self.is_aborted:
            return
```

And of course each different host could set up its own trigger for setting Pyblish's `is_aborted` setting somehow.

Is that what you mean?

**Comment by mottosso** [comment]
Thanks for your input, @BigRoy.

> Maya does allow to show a progress bar and capture whether the user has requested it to 'quit' (I think it takes the escape button as quitting.

That's an interesting thought for a Maya implementation of this. I haven't had any experience with that one, would it be possible to provide an example? Does it actually cancel an operation, such as subdividing a heavy mesh?

> We could add a self.is_aborted attribute on all plug-ins that gets set to True when the user has requested to stop.

That should work, at least for loops. What I had in mind initially was a little less involved and more brute force; as in _killing_ the thread running a particular command. Might not always (or ever) work, but might function as fallback/default, cross-software behaviour when a host-specific solution isn't available.

I'd be happy to have your solution implemented; it would currently go into [Plugin.process](https://github.com/abstractfactory/pyblish/blob/master/pyblish/plugin.py#L140) which is handling the main loop.

**Comment by BigRoy** [comment]
You would have to use the **[progressBar](http://download.autodesk.com/us/maya/2010help/CommandsPython/progressBar.html)** command from Maya.

Here's a context manager I've used here and there:

``` python
import maya.cmds as mc

class MayaProgressBar(object):
    def __init__(self, step=1, maxValue=100, status="Processing...", useInternalCounter=True, inMainWindow=True):
        self.maxValue = maxValue
        self.status = status
        self.step = step
        self.internalCounter = 0
        self.inMainWindow = inMainWindow
        self.useInternalCounter = useInternalCounter

    def __enter__(self):
        if self.inMainWindow:
            import maya.mel as mel
            self.progressBar = mel.eval('$tmp = $gMainProgressBar')
            self.window = None
        else:
            self.window = mc.window(title=self.status)
            mc.columnLayout()
            self.progressBar = mc.progressBar(w=300)
            mc.showWindow(self.window)


        progressStartKwargs = {'e':True, 'isInterruptable': True, 'beginProgress': True, 'status': self.status, 'maxValue': self.maxValue}
        mc.progressBar(self.progressBar,**progressStartKwargs)

        # Fix for hanging previous progress (force cancel it and restart)
        if mc.progressBar(self.progressBar, query=True, isCancelled=True):
            mc.progressBar(self.progressBar, e=1, endProgress=True)
            mc.progressBar(self.progressBar,**progressStartKwargs)

        return self

    def setStatus(self, s):
        mc.progressBar(self.progressBar, e=1, status=s)

    def update(self):
        if mc.progressBar(self.progressBar, query=True, isCancelled=True):
            raise RuntimeError("Process interrupted.")

        if self.useInternalCounter:
            self.internalCounter += 1
            if self.internalCounter % self.step == 0:
                mc.progressBar(self.progressBar, e=1, step=self.step)
        else:
            mc.progressBar(self.progressBar, e=1, step=1)

    def __exit__(self, type, value, traceback):
        mc.progressBar(self.progressBar, e=1, endProgress=True)
        if self.window is not None:
            mc.deleteUI(self.window)
```

This will raise a RuntimeError when the user cancelled the operation.
Usage example:

``` python
amount = 10000
with MayaProgressBar(maxValue=amount) as progress_bar:
    for x in xrange(amount):
         progress_bar.update()
```

**Comment by mottosso** [comment]
Looks like we've got a winner!

**Comment by mottosso** [comment]
Come to think of it, this was implemented in the current GUI here: https://github.com/pyblish/pyblish-qml/issues/7#issuecomment-64429839.

But it only allows cancelling in-between plug-in processing; not during.
