### ISSUE TITLE
Project website

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-base#13]
We'll need a proper website with logo and introduction to the project. If this is you, let us know here!

Address suggestions:
- publish.io (n/a)
- publish-app.org
- publishcg.io

**Comment by ljkart** [comment]
I would like to vote for publish-cg.io or publishcg.io

**Comment by madoodia** [comment]
thepublish.io

**Comment by tokejepsen** [comment]
instead of a website, couldnt we use ReadTheDocs or some other auto-generated site?

**Comment by mottosso** [comment]
Sure, I personally like RTD for documentation, but as a website I'm thinking more in terms of a first-impression. There could then be links to RTD, the github project and wiki from there. The idea is to provide a "shopfront" for Publish; something that will just give a really good first impression, before actually getting into what it does and how to use it.

Some examples of what I'm thinking:
- http://balloons.io/
- http://redis.io/
- https://asciinema.org/
- http://flowbox.io/

**Comment by ljkart** [comment]
I agree Marcus because it should be our front face to the people rather showing the codes.

**Comment by tokejepsen** [comment]
Cool, sounds good. Personally I like simplicity and straight to the point:
- Video showing the potential
- Mission statement
- "Get it, or collaborate" buttons

**Comment by mottosso** [comment]
What do you guys think about _pypublish_? E.g.
- www.pypublish.com
- http://pypublish.io
- pypublish.org

It's available, both as a domain and on PyPI, and to the point about what it is - a Python Publishing framework.

**Comment by achayan** [comment]
+1 for pypublish.org

**Comment by mottosso** [comment]
I've initiated a GitHub Pages site here:
http://abstractfactory.github.io/publish/

I'd propose hosting our site here - which is technically a separate branch in the main repository called `gh-pages` - and redirect `pypublish.org` - or whichever domain-name we end up with - to it.

Currently, editing of this page is done via the GitHub page generator, which is simple, but not very flexible. Down the line, I'd vouch for [Jekyll](http://jekyllrb.com/) which is supported by GitHub and enables some additional features, such as individual pages and additional themes.

**Comment by mottosso** [comment]
How about,
- www.pyblish.org
- www.pyblish.io
- www.pyblish.com

Reasoning being, more room to breathe as the word "publish" is quite occupied across the world wide webs, forcing us to compromise with our brand name. Pyblish is untouched, sounds like Publish, touches on the fact that it is Python and is shorter and easier to say than PyPublish.

I personally prefer Publish, but what can you do.

**Comment by tokejepsen** [comment]
+1 for Pyblish

**Comment by achayan** [comment]
www.pyblish.org +1

**Comment by ghost** [comment]
+1 for Pyblish

**Comment by mottosso** [comment]
Ok folks, a brand new website is up.

### www.pyblish.com

This represents the first impression we give to our users, so it's extra important that it looks and reads as good as possible. Should you find the time, do read through it and look for things to improve. It is a regular GitHub repository that you can fork, clone and edit at your own leisure. Any issues should also be kept in there.
- https://github.com/pyblish/pyblish.github.io

### .com/.org

I was initially looking to get a org domain, but all I could find was those twice as expensive as a .com domain. If there is interest, we could start a donation account for ourselves and our users to share some of the costs, that way we can have multiple domains. As it turns out, pyblish is very available amongst domain names.

Let me know what you think.

**Comment by mottosso** [comment]
We now have both **.com** and **.org**, thanks to @madoodia who contributed to the first year of the domain!

It'll take around 24 hours for it to kick in, but tomorrow, these will both work.

http://pyblish.org
http://pyblish.com

**Comment by madoodia** [comment]
I will be happy if i can help.
Good Luck team.

On Mon, Sep 22, 2014 at 10:54 AM, Marcus Ottosson notifications@github.com
wrote:

> We now have both _.com_ and _.org_, thanks to @madoodia
> https://github.com/madoodia who contributed to the first year of the
> domain!
> 
> It'll take around 24 hours for it to kick in, but tomorrow, these will
> both work.
> 
> http://pyblish.org
> http://pyblish.com
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/abstractfactory/pyblish/issues/13#issuecomment-56337301
> .

## 

Bests,
madoodia

**Comment by mottosso** [comment]
This is live, any issues about the site, log them here:
https://github.com/pyblish/pyblish.github.io
