### ISSUE TITLE
Bad user-configuration causes issues with GUI

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-base#134]
As discovered by @davidmartinezanim, having an invalid or otherwise corrupt user-configuration may cause the Pyblish QML gui to malfunction.

This shouldn't happen. Investigate why and resolve it.

**Comment by mottosso** [comment]
@davidmartinezanim I'm having trouble re-producing this.

I made a corrupt user-configuration, but the GUI and everything else seems to be running fine still..

Here's my configuration.

**.pyblish**

``` bash
[45gfkgk2d:}}%^
```

Do you remember how you got this error?

**Comment by ghost** [comment]
I'm afraid I don't.  All I remember is that deleting the file forced
Pyblish to re-create it from scratch and that fixed the issue.

**Comment by mottosso** [comment]
Pyblish shouldn't be re-creating any user-configuration, it must be manually created by a user.

If it's okay with you, let's re-open this issue if it happens again.
