### ISSUE TITLE
Writing tests

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-base#14]
I had an idea about trying to implement Publish using a test-driven development style, which in a nutshell means to write tests before code.

In our case, since we're developing for content creation, tests could potentially take the form of content. Content that would be successfully published with Publish once development on a particular feature is complete.

I've tried summarising a suggested workflow for working with tests, as well as provided some examples on tests that should run successfully once Publish is in a working state. 

What are your thoughts on this?

https://github.com/abstractfactory/publish/wiki/Tests

**Comment by fredrikaverpil** [comment]
I think that's a great idea. I've only used nosetests before, and sparsly. So I can't comment much on which test system to go with.

I'm guessing that tests needs to be performed within Maya. Should a site-packages directory (or virtualenv) be bundled within the repo, for easier packages import within Maya?

**Comment by mottosso** [comment]
Thanks, I'm glad you like it.

The tests should run with Publish once its in an executable stage. The process might be something like this:
1. Test is written
2. `pip install publish`
3. Publish is run to publish the scene, the scene should publish successfully.

If the scene isn't published successfully, something is wrong with Publish, not the test. Tests are the ultimate authority here.

Off the top of my head, I'm thinking Publish should be available via the File menu from within Maya, and in similar locations in other apps.

**Comment by mottosso** [comment]
This has been deprecated in favour of examples. See the examples in pyblish-maya for example. Pun!
