### ISSUE TITLE
Making Instances Mandatory

### ISSUE THREAD

**Issue by ghost** [pyblish/pyblish-base#157]
Is it possible to make an instance mandatory so it cannot be disabled? The reason why I'm asking is that in my case, the instances are not defined by Quick Selection Sets but by the scene itself and I would like it so it cannot be disabled. Is that possible with the current implementation?

Thanks

**Comment by mottosso** [comment]
I suppose it could be added, but why?

**Comment by ghost** [comment]
Not a major one. I's just that it feels weird being able to disable the instance. That's all.

**Comment by mottosso** [comment]
Ah, okay. I'll keep it open in case you encounter an issue with it and to hear others thoughts about it, but I'm not sure this is a terribly practical feature.

**Comment by mottosso** [comment]
Closing for now, feel free to re-open if you experience any problems with it.
