### ISSUE TITLE
UI unable to cope with a really long list of plugins

### ISSUE THREAD

**Issue by ghost** [pyblish/pyblish-base#158]
Even though that I haven't reached the bottom part of the interface with the plugins I'm creating, I'm getting dangerously close. After resizing the window it feels like the part displaying the plugins does not contain a scroll bar and as such, the user would never see the ones that don't fit within the interface.

Could you add a scroll bar so we can see all of them?

**Comment by mottosso** [comment]
Ah, yes, this is a bug.

Scrolling will work like in the terminal.

Thanks for the report!
