### ISSUE TITLE
Plugins that run on all families

### ISSUE THREAD

**Issue by ghost** [pyblish/pyblish-base#160]
Is it possible to have plugins that run on all families instead of being family specific?

I'd like to create some validators that run regardless of the family to which an instance belongs.

**Comment by mottosso** [comment]
Yes. The family is `*` (wildcard)

Would it be okay to ask questions in the [Gitter](https://gitter.im/pyblish/pyblish) before opening up an issue?
- https://gitter.im/pyblish/pyblish
