### ISSUE TITLE
Family Depth Limit

### ISSUE THREAD

**Issue by ghost** [pyblish/pyblish-base#161]
At the moment I have something simple like:

`typeOfChar.typeOfFile`

But I believe that you can have multiple nested levels. Something like:

`characters.heroChars.TypeOfFile`

If that's the case, is there a limit of depth that a family can have?

Also, is it possible to have plugins affect all the sub-levels? That would mean that I can create plugins of things that apply to all `characters`, others that are specific to `heroes` and others that are specific to the deepest level.

I'm just curious about what's the best way to get the most of the system.

**Comment by mottosso** [comment]
At the moment, dots in the name has no special effect; it's just a string.

In the future, the idea is to implement Namespaces, which I think will do what you're looking for.
https://github.com/pyblish/pyblish/issues/97

Until then, you can simply add each level to the supported list of families; this is much like what an actual implementation may do.

``` python
# I will run on all levels
families = ["characters", "characters.heroChars", "characters.heroChars.TypeOfFile"]

# I will only run on the lowest level
families = ["characters"]
```

**Comment by ghost** [comment]
Thanks for the information, Marcus

The idea of namespaces does indeed sound good. In the meantime I will be doing what you mentioned in the comment above.
