### ISSUE TITLE
Default Log Call to type string

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-base#174]
#### Problem

Running `self.log.info(1)` errors out.
#### Solution

Default convert all data to log call to type string.

**Comment by mottosso** [comment]
Would this be better suited for the Nuke repo? Or have you noticed the problem in other integrations too?

**Comment by tokejepsen** [comment]
Got this in Maya. Dunno if its specific to QML though.

**Comment by mottosso** [comment]
Oh, where did the error occur? Could you post it?

**Comment by tokejepsen** [comment]
So the specific example is this extractor;

``` python
import os
import getpass

import pyblish.api


@pyblish.api.log
class ExtractDeadlineData(pyblish.api.Extractor):

    families = ['deadline.render']
    hosts = ['*']

    def process_instance(self, instance):
        self.log.info(instance)
```

And here is the error message:

![capture](https://cloud.githubusercontent.com/assets/1860085/7560446/2ce64cca-f7bb-11e4-852e-b8b09e5e3f60.PNG)

**Comment by mottosso** [comment]
Yes, that's a bug.

Investigating.

**Comment by mottosso** [comment]
In the meantime, you can work around it by ensuring that you only log string types.

**Comment by tokejepsen** [comment]
yeah, been converting the log calls to strings.

**Comment by tokejepsen** [comment]
This has been fixed.
