### ISSUE TITLE
Existing publishers/references

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-base#18]
If anyone knows of any existing publishers out there, either in the form of github projects, or just glimpses of it in showreels, could you share it here?

The only one I know of is [Quality GuAard](http://www.martintomoya.com/tools_info.html) but I remember seeing reels with publishers before, I just can't seem to find any.

**Comment by achayan** [comment]
Some weblinks

https://www.youtube.com/watch?v=CweaPWPFkAI  # Asset templates in Maya
http://opensourcevfx.org/2010/01/openpipeline/

**Comment by BigRoy** [comment]
Shotgun is providing publishing solutions in their newer iterations of their 'Shotgun Pipeline Toolkit':
[https://toolkit.shotgunsoftware.com/entries/23469612-Publishing-and-Sharing-your-Work](https://toolkit.shotgunsoftware.com/entries/23469612-Publishing-and-Sharing-your-Work)

If you follow their blog you'll see they are re-iterating the designs for the UIs of their toolkit and they should currently be reimplementing the publishing UIs based on user feedback. The latest iterations of the asset browser looks much better than the one before, so I wonder how they optimize the next version of the multi-publish tool! Nevertheless it's interesting to see what's already there.

**Comment by mottosso** [comment]
Thanks @achayan, but I'm not sure whether asset templates or Open Pipeline actually provides any hint towards publishing. Could you expand a little on your thoughts behind these links?

> Shotgun is providing publishing solutions in their newer iterations of their 'Shotgun Pipeline Toolkit'

That's a great example. I haven't used it, but have seen their videos presenting it. Doesn't seem to ship with any mechanism of tests/validations however, do you know whether that's an upcoming feature?

Either way, their breakdown of how it works in the link you provided should prove useful as reference, both for things to do but perhaps more importantly, what _not_ to do.

## FTrack

FTrack provides a solution similar to shotgun; also without validations along with a seemingly hard-coded naming convention. (something else we should avoid!)
- http://support.ftrack.com/customer/portal/articles/1335406-maya-integration
- http://api.ftrack.com/developing/api_tutorial/publishing.html

**Comment by BigRoy** [comment]
I don't think either Shotgun or FTrack's publishing solution does any checking. Keeping that in mind I think we might need to keep in account the Use Cases where people would only want to use the Selection and Validation steps of _Publish_. This way even if studio already adopted something like Shotgun then they still would be able to get something awesome out of this without getting in the way. Also this would be totally viable because it's basically a set of steps/actions. What do you think?

**Comment by mottosso** [comment]
> I don't think either Shotgun or FTrack's publishing solution does any checking. Keeping that in mind I think we might need to keep in account the Use Cases where people would only want to use the Selection and Validation steps of Publish.

I agree, it's certainly worth keeping in mind, but I personally feel a bit overwhelmed with the potential and configurability at this early stage and would opt to keep things plain and dull until later on.

**Comment by tokejepsen** [comment]
Just as a note, but Shotgun has their equivalent of plugins called hooks. These are run post and pre an app, where you can do various checks and validations.

**Comment by ljkart** [comment]
I agree [tokejepsen](https://github.com/tokejepsen) that shotgun having hooking mechanism to hook other tools to it , like Alembic cache creation. we can plug other tools as hooks.

**Comment by BigRoy** [comment]
That's great actually, because we're looking into separating the **Actions** like **Validation** and **Extraction**. Thus in such a case _Publish_ could be used with that hook to only perform the validation and fixes pre- and/or post-publish leaving the rest to Shotgun.

**Comment by BigRoy** [comment]
Have a look at _ftrack_'s new Location API technology to see how one could streamline the _positioning of the output files_. Here's some [more information about ftrack 3.0](http://www.fxguide.com/featured/ftrack-debuts-v3-at-siggraph/).

**Comment by BigRoy** [comment]
The technology we have been discussing for _Publish_ kind of sounds like a Dependency Graph and/or State Machine. Whilst reading through [some technical bits on FXGuide](http://www.fxguide.com/quicktakes/siggraph-2014-digipro-and-day-1/) I spotted something called [Depend](http://www.dependsworkflow.net/index.html) which is: 

> Depend is an open source scientific workflow management system tuned specifically to address the needs of researchers and visual effects artists

Especially since it utilizes a simple and clear node graph this could act as reference, or maybe even a core library/foundation. What do you guys think?

**Comment by tokejepsen** [comment]
Depends sounds very interesting. If anything would definitely be something to plug into.

**Comment by tokejepsen** [comment]
Dunno if u guys have seen this, but this is very interesting for this and any open source project; http://fabricengine.com/fabric50/

**Comment by mottosso** [comment]
This is a big win. It's practically safe to start investing time into
developing with Fabric now. However, let's try and not make this issue
about Fabric, unless it's relevant as an alternative publishing solution.

On 12 August 2014 15:20, Toke Jepsen notifications@github.com wrote:

> Dunno if u guys have seen this, but this is very interesting for this and
> any open source project; http://fabricengine.com/fabric50/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/abstractfactory/publish/issues/18#issuecomment-51912270
> .

## 

_Marcus Ottosson_
konstruktion@gmail.com

**Comment by mottosso** [comment]
References added to https://github.com/abstractfactory/pyblish/wiki/What-is-publishing
