### ISSUE TITLE
Selecting using objectSet/Selection Sets

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-base#19]
There's been some enquiries about why using sets is a good idea so I'll try and take a step back and look at some of the concerns sets help solve.

For starters, by "[selecting](https://github.com/abstractfactory/publish/wiki/selection)", I'm referring to both specifying _what_ to publish but also _how_ to publish it.

Here are some suggested ~~requirements~~ assumptions.
1. Publishing is an incremental operation
2. Not everything in a working scene may be meant for publishing
3. Publishing is a common operation that happens often
4. Visualising what is about to be exported is important for quality control
5. Publishable scene should be testable
6. Some nodes can't fit in a transform node (Maya)

I don't particularly mind which exact node carries which data, sets just seemed to me to solve these issues quite well and I didn't see a reason not to use them, but I'd be happy to hear what you find discouraging about them.
1. By incremental, I mean that once settings for a publish has been set, such as frame ranges and author and what not, they most likely won't need to be changed and can remain throughout the next publishes. In the case of sets, attributes can be stored on the node that hold these settings. If these were to instead be stored within the tool, we would either have to get clever and let the tool know which persistent settings to look up or reset the tool upon each run, which would invite inconsistency between publishes.
2. (and 3). Let's talk rigging as an example. Most things may be located within an object hierarchy, but some things may be work in progress, not being ready for this "release". Other things may never be meant to follow along; such as measurements, statistics or other debug nodes. We will need a way for artists and TDs to distinguish between what goes, and what stays. With sets, included items are visible from the outliner and can be modified by anyone.
   
   For example, including a set of geometry: ![](https://camo.githubusercontent.com/c8a3bccb566a53bfcb0653c6ac97e9e83c41cd1c/68747470733a2f2f646c2e64726f70626f782e636f6d2f732f756739373278646265356537776b662f746573742532432d6d6f64656c2e706e67)
3. I personally feel that it should be as simple as possible to perform a publish, and that the UI then should offer a minimal set of configuration options. After an initial publish, the only new information between one publish and the next could potentially be a changelog or comment. Can you think of anything else?
4. When everything is pre-configured within a scene, publishing can be batchable and testable without options or GUI.
5. There may be nodes involved in a publish that a transform node can't carry; such as other sets, script nodes or any arbitrary non-dag node
   
   ``` bash
   # For example, from the command-line
   $ publish --path=/spiderman/my_scene.mb
   ```

What do you think about these requirements and their solutions?

**Comment by tokejepsen** [comment]
I'm finding it hard to imagine the same workflow in other apps, which is why I'm leaning towards having tools/GUIs for visualizing and setup. Any data that the GUIs modify gets stored on the nodes themselves, which makes it batchable/testable.

**Comment by mottosso** [comment]
Mm, you may be right.

What are your thoughts on the assumptions? Do they make sense?

**Comment by tokejepsen** [comment]
yeah, only questioning #1, where I'm guessing you mean that you have different versions of assets and shots?

**Comment by mottosso** [comment]
Yes. By incremental I mean that publishes happen many times, usually with similar or identical settings.
~~https://github.com/abstractfactory/publish/wiki/Requirements#req13~~ Sorry that link didn't relate to the same issue.

That is a reason for storing settings together with what is being published, as opposed to in the tool. So that any artist or TD can open up a scene from anyone and produce a publish in accordance with how it was previously published.

**Comment by madoodia** [comment]
I think we should use a way that be usable on all supported softwares(i mean 3d and 2d softwares)
there is equivalent sets on nuke?
on the other hand i think we can create own custom node with our attributes and use it in every scene.(this is just an idea)

**Comment by mottosso** [comment]
Ok, putting sets away, let's focus on what they solve and what alternatives there are. :)

A custom node is an idea, some studios does that, but it would constrain users of Publish to use our custom node and I honestly can't see any added benefit to having one, unless we make it more like a set which possibly defeats the purpose.

Let's go one at a time.
1. Publishing is an incremental operation

The scenario I'm imagining is for users to configure what to publish once, and then never configure it again. Version 110 publishes has identical settings as version 2. What better way than to persistently store settings about a publish, then in the instances being published? If we store it in the tool, where do we persist it? Should it persist?

**Comment by tokejepsen** [comment]
I think maybe we should look at what render management softwares are doing for integration. Like I know that Deadline attaches all their data on "defaultRenderGlobals", which can't be access without explicit name

**Comment by BigRoy** [comment]
I like your picks on 'configuring' what to publish within the scene and I wonder if that is considered a nice approach in the industry. We had a similar workflow in-house during publishing as well, but working with interns and freelancers meant from time to time people forgot to select/configure all the relevant objects in the scene. Since departments from one workspace to another can be pretty disconnected during tight deadlines it's very hard to spot that things are missing; this is even worse if the scene is heavy and hard to 'check'.

Our newer workflow is built-up of an _algorithm_ per publishing process that dynamically looks up all relevant nodes in the scene. Currently we only use 'selection' based publishing for the "modeling" and "lookDev" (= shading) workspace. But publishing an animation or FX scene is just way too hard to _configure by hand_ per scene (too many objects).

Nevertheless I feel that _any_ idea presented here has pros and cons and wouldn't want to take anyone's workflow away if he or she went with _Publish_. Instead I'd opt for 'selection components' that are configurable stacks that define what will be picked for publish.

One could write a "objectSet" component that takes all objects in an object set to allow for the behaviour described above. Or an "tagged with attribute" Selector component to allow the studio to tag objects with an attribute to include it in a publish, etc. This way we're allowing for far more (and even complex but modular) publishing situations.

Also have a look at the draft I wrote for [Selection->Architecture](https://github.com/abstractfactory/publish/wiki/Architecture,-Selection)

**Comment by mottosso** [comment]
> Our newer workflow is built-up of an algorithm per publishing process that dynamically looks up all relevant nodes in the scene.

This is how I'd envision it too, but the issue is which variables we can expose to such an algorithm. I'm assuming that the assets in your shop is tailored to your publishing framework, and as such you are able to make assumptions about them; such as where to find meshes for pointcaches, or controllers for animation exports.

As mentioned elsewhere, it's quite possible that we'd have to enforce such tailoring for this to work, but if possible I would opt to keep any tailoring 100% optional and let those without advanced needs use Publish with as little effort as possible.

> Instead I'd opt for 'selection components' that are configurable stacks that define what will be picked for publish.
> 
> ...
> 
> Also have a look at the draft I wrote for Selection->Architecture

This sounds like a solution to the concerned I just mentioned. Modularity facilitates keeping things optional and for things to go beyond the initial expectations of the project.

+1

**Comment by tokejepsen** [comment]
+1 for selection components

**Comment by mottosso** [comment]
Had a quick thought, inspired by how Softimage does things.

For those who don't know Softimage very well, in Softimage, assets are typically bundled up into a type of group called "Model". A Model is essentially a mini-scene, capable of storing any node you could normally store in a scene. Models can be nested. The actual scene is in fact one big Model.

The benefit of this is that you can safely encapsulate everything related to a particular asset, including non-DAG nodes like animation and deformers and move this in-between scenes safely.

This makes the extraction part of publishing very straightforward; as it involves simply exporting the model. All settings related to a particular asset also have a definite place to be, on the model itself.

We could introduce a similar concept in Maya, possibly like this: Each node with the attribute "family" (e.g. is it a model, rig, shader etc.) is treated similar to a Model within Softimage. Nodes parented underneath a family-node would be part of this asset, and children with a "family" attribute would be treated as a nested asset.

From there, selecting individual nodes in a scene is not longer on the table, instead we select Family-nodes. Anything parented under it is part of a family, possibly excluding nodes with a particular attribute (e.g. "exclude"). It also works on objectSet's, for those who'd like to use it, as it acts similar to a regular transform.

Not sure it makes a lot of sense, but it solves an issue I encountered in regards to finding individual nodes in a scene (e.g. "all nurbs curves") and finding individual "assets" (e.g. a model, a rig). It means we wouldn't be responsible for selecting or filtering nodes themselves, but only concern ourselves with the higher-level concept of an "asset"; i.e. anything tagged with a "family" attribute.

**Comment by mottosso** [comment]
Closing this, as it's covered by having made the responsibility into plugins.
