### ISSUE TITLE
Include current working directory with CLI

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-base#193]
### Goal

To simplify learning by exposing the current working directory for plug-ins when running Pyblish via the command-line. This way, no registration or environment variable needs to be altered for simpler tasks and whilst learning.
### Implementation

Register the result of `os.getcwd()` when publishing via the command-line.

``` bash
$ ls
myplugin.py
$ cat myplugin.py
import pyblish.api

class MyPlugin(pyblish.api.Plugin):
  def process(self):
    print("Hello World")
$ pyblish publish
Hello World
```

**Comment by mottosso** [comment]
Already possible with `--plugin-path` flag.

``` bash
$ pyblish --plugin-path=c:\my_plugins publish
```

**Comment by larsbijl** [comment]
is this still something we want?
I think it makes more sense for it to be explicit as you have shown. less magic and also less change for a stray validator to come into the mix because you have one in your home directory and didn't realise.

**Comment by mottosso** [comment]
I'm happy for you to decide this.

**Comment by larsbijl** [comment]
explicit is better then implicit.
we should explain how to make it easier when testing. 
I can see people abusing it for convenience sake.
