### ISSUE TITLE
Google Groups/Mailing list

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-base#20]
Do you think we need a Google Groups? E.g. like the [Maya-Python group](https://groups.google.com/forum/#!forum/python_inside_maya).

The GitHub issues are essentially like a forum (at least the way we've been using it) but maybe it isn't as great for archiving and searching amongst older posts, or for more casual or general conversations.

**Comment by mottosso** [comment]
How about an IRC channel, with a client like https://github.com/hexchat/hexchat

The goal is to more easily introduce interested contributors to the project, without having them post in issues directly, or sent personal emails to anyone, and to also be able to communicate with each other in a quicker fashion.

The disadvantage being spreading information about the project out across multiple places. At the moment, its fairly self-contained here on GitHub. Chat's on the other hand aren't public, and they possibly should be.

**Comment by achayan** [comment]
I think google group is more convenient for discussions. We can organize  things much more and we can interact inside from our mail itself.

**Comment by BigRoy** [comment]
I think Google Group could be useful for this. It's also something that one easily feels 'free' to join and add to the conversations if you're new to _publish_ instead of feeling like a newbie trying to comment on issues. I guess Github is still more for the programmers among all of us and a mailing list can easily be joined by artists. To be honest I wouldn't know if that's popular among non-programmers as I only know from my own experience.

**Comment by mottosso** [comment]
I've created a group here:

https://groups.google.com/forum/#!forum/pyblish

But will refrain from making it publicly accessible until it is clear that we will post in it frequently. There is nothing more discouraging to newcomers than an inactive usergroup.

Me and @tokejepsen spoke about making this issues-section more about bugs and tasks, as opposed to a forum for discussion, so that we can make assignments and keep track of who does what. We could then more discussions over the the group.

**Comment by mottosso** [comment]
Usergroup is now for discussion and user help, whereas Issues are for bugs, tasks and features.
