### ISSUE TITLE
Extractor negative order

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-base#206]
When an extractor has a negative order from the default pyblish.api.Extractor.order - 0.1, the plugin will execute in the validation stage.

![capture 1](https://cloud.githubusercontent.com/assets/1860085/8591380/d6dbdb4a-261f-11e5-84d7-3706acc0b259.PNG)

**Comment by mottosso** [comment]
Just to be sure, you are running Pyblish 1.1.2? Prior to then, this is the expected behaviour as negative values weren't supported.

**Comment by tokejepsen** [comment]
> Just to be sure, you are running Pyblish 1.1.2?

Yup
