### ISSUE TITLE
Coding tasks

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-base#21]
Wanted to pitch what the coding tasks would be;
- Nodes to publish function
- Output Classes
  - Validators
  - Output Data templates
- Output Data Writers
  - File destination

Let me know what you think?

**Comment by mottosso** [comment]
Looks good to me. How about this for an interface:

``` python
>>> # Read from pre-determined node in scene; either those with a "publishable"
>>> # attribute, or some other name-convention. This could be where clients
>>> # overrides the predicates. The return value could be a dictionary with
>>> # the name of each instance and its associated controls/meshes/configuration
>>> selection = publish.read_selection()  # -> (dict)

>>> # Based on each corresponding "class" per instance, run
>>> # the associated validators and return whether or not it
>>> # succeeded.
>>> valid = publish.validate(selection)  # -> (bool)
>>> if valid:
...     # Begin export; first to a temporary location
...     # and then to a workspace-relative location.
...     extracted = publish.extract(selection)  # -> (str): absolute path
...     # This is the optional part, and may utilise the template
...     # system that Liju is working on.
...     publish.conform(extracted)  # -> (bool): success

>>> # As a convenience function, this could peform all of the above.
>>> if not publish.publish():
...    raise Warning
```

**Comment by tokejepsen** [comment]
Looks cool.

```
>>> valid = publish.validate(selection)  # -> (dict) need to validate each nodes separately
```

Reminds me that there needs to be some auto fixes and user feedback, so the following can happen

```
>>> if valid:
... # publishing valid nodes
else:
... # autofix or tell user the problem
```

**Comment by mottosso** [comment]
Yes, good catch. `validate()` could return each validator that failed, so it could be visualised in the GUI, potentially offering the user a choice of whether or not to fix it.

``` python

failures = publish.validate(selection)  # -> (list): List of exceptions
if not failures:
    # publish
else:
    for failure in failures:
        print "{0} failed".format(failure)
```

**Comment by mottosso** [comment]
Before writing any code, I would suggest mocking up a scene with an asset and relevant tagged/objectsetted nodes. That way, we will know what to expect out of it.

What do you think about writing code to try and publish **[this](https://github.com/abstractfactory/publish/tree/master/resources/tests/full/individual_asset_test/Peter/model)**? We could modify the file if needed until it publishes successfully. From there, we'll know how liberate/restricted we can be about what to include and how to include it.

As for which validators to start out with, let's pick some from [Quality GuaArd](http://www.martintomoya.com/tools_info_files/qg8.png), e.g.
- Mesh history
- Unconnected intermediate objects
- Empty poly meshes

It may also be helpful to make a scene for which we know the publish will fail, so that we have something to work with when it comes to dealing with invalid output.

**Comment by tokejepsen** [comment]
Yeah, could start with that. After the discussion on TechArt with @BigRoy, I think the validators need to thought about as more self contained, so they can function on their own as well as triggered by classes.

**Comment by mottosso** [comment]
Submitted a pull-request here: [**Pull-request**](https://github.com/abstractfactory/publish/pull/22), but perhaps it is better we continue the discussion in this issue instead.

Here's the specifications related to your initial tasks:

> Nodes to publish function

Published nodes are derived via the [`select()`](https://github.com/mottosso/publish/blob/c18865c2b54bb32a53386f3ba1f3c40181874734/publish/maya.py#L109) method and is simply looking up objectSets with a pre-defined attribute; [`publishable`](https://github.com/mottosso/publish/blob/c18865c2b54bb32a53386f3ba1f3c40181874734/publish/maya.py#L74). Anything contained within the objectSet is extracted; i.e. exported.
- See here [`select()`](https://github.com/mottosso/publish/blob/c18865c2b54bb32a53386f3ba1f3c40181874734/publish/maya.py#L109)
- See here [`publishable`](https://github.com/mottosso/publish/blob/c18865c2b54bb32a53386f3ba1f3c40181874734/publish/maya.py#L74)

> Output Classes

The main class/family being extracted is "model", but also included is the concept of a "review" class/family. Nothing is happening to it, but the proposed use would be to make a playblast of the selected cameras.
- See here [Families](https://github.com/mottosso/publish/blob/c18865c2b54bb32a53386f3ba1f3c40181874734/publish/maya.py#L176)

> Validators

A few validators are included [here](https://github.com/mottosso/publish/blob/c18865c2b54bb32a53386f3ba1f3c40181874734/publish/maya.py#L58) but do nothing other than illustrate where and how they are used.
- See here [Validators](https://github.com/mottosso/publish/blob/c18865c2b54bb32a53386f3ba1f3c40181874734/publish/maya.py#L58)

> Output Data templates

The algorithm to figure out an exact extraction location is [here](https://github.com/mottosso/publish/blob/c18865c2b54bb32a53386f3ba1f3c40181874734/publish/maya.py#L220)

> Output Data Writers

Data is written via the use of FIle --> Extract selection
- See here [Export](https://github.com/mottosso/publish/blob/c18865c2b54bb32a53386f3ba1f3c40181874734/publish/maya.py#L230)

> File destination

Sorry, what was the difference between this and "Output Data templates"?

### [More info in the Pull-request >>](https://github.com/abstractfactory/publish/pull/22)

**Comment by mottosso** [comment]
Closing this and continuing in #32
