### ISSUE TITLE
Publish Target

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-base#225]
### Goal

Facilitate re-use through publishing to a global target. For example, publishing a rig for use in multiple projects, a render for use in multiple shots or a texture for use with multiple models.
### Implementation

Not having given it much thought, I'd imagine `target` to be specified prior to publishing.

``` python
import pyblish.api
pyblish.api.register_target("project")
pyblish.api.register_target("studio")
```

Where `target` is accessible in plug-ins.

``` python
class MyPlugin(...):
  def process(self, instance):
    if pyblish.api.target == "project":
      # do A
    else:
      # do B
```

Where `pyblish.api.target` is either the last registered target or set manually..

``` python
pyblish.api.target = "studio"
```

Graphically, the target could be visualised as a top-most selection.

![image](https://cloud.githubusercontent.com/assets/2152766/9578861/61a2ff76-4fe5-11e5-93f4-79d37e6213ff.png)

**Comment by mkolar** [comment]
This is a great idea, that could potentially open lots of doors.

**Comment by mottosso** [comment]
This one should be a cakewalk to implement, at least on the non-UI side, pull requests are welcome!

**Comment by larsbijl** [comment]
I've added a pull request that tries to implement what was outlined by Marcus.

 the only deviation being that instead of using a variable like assignment,  I've gone for a similar approach to how hosts are currently shown.  this is to keep it consistent.

`if pyblish.api.current_target() == "project":`

and

`pyblish.api.register_target("project")`

if a target is set before it will be removed and re-added as the last entry to the target list.

**Comment by mottosso** [comment]
Nice work, I think you made the right call about the deviation.

**Comment by mottosso** [comment]
Do we want plug-ins to only show if they align with a target, similar to host- and family-specific plug-ins?

``` python
import pyblish.api

class CollectStudioTargetInstances(pyblish.api.ContextPlugin):
  order = pyblish.api.CollectorOrder
  target = "studio"

  def process(...):
    ...
```

In the main example above, it suggests that it is only relevant for use within a plug-in.

**Comment by mottosso** [comment]
### Usage example

This integrates collected content into each target.

``` python
"""Publish to multiple targets"""

import os
import glob
import shutil
import pyblish.api


class Collect(pyblish.api.ContextPlugin):
    """Collect .exe files from cwd"""
    order = pyblish.api.CollectorOrder

    def process(self, context):
        instance = context.create_instance("MyInstance")
        instance.data["dirname"] = context.data["cwd"]
        instance[:] = glob.glob("./*.exe")


class Integrate(pyblish.api.InstancePlugin):
    """Integrate to multiple targets"""
    order = pyblish.api.IntegratorOrder

    def process(self, instance):
        home = os.path.expanduser("~")
        srcdir = instance.data["dirname"]

        for target in pyblish.api.registered_targets():
            dstdir = os.path.join(home, target)

            try:
                os.makedirs(dstdir)
            except OSError:
                pass  # Dir already exists

            self.log.info("Integrating \"%s\" to \"%s\"" % (srcdir, dstdir))
            for fname in instance:
                src = os.path.join(srcdir, os.path.basename(fname))
                dst = os.path.join(dstdir, os.path.basename(fname))
                self.log.info("Copying %s -> %s" % (src, dst))
                shutil.copy(src, dst)


pyblish.api.register_plugin(Collect)
pyblish.api.register_plugin(Integrate)

# Comment these out to simply not integrate anywhere
pyblish.plugin.register_target("studio")
pyblish.plugin.register_target("home")


if __name__ == '__main__':
    import pyblish.util
    context = pyblish.util.publish()

    # Report
    for result in context.data["results"]:
        print("%s" % result["plugin"])
        for record in result["records"]:
            print("\t %s" % record.msg)
```

@larsbijl if you have something different in mind, here and now would be a good time to share!

**Comment by larsbijl** [comment]
The method currently implemented would allow for more flexibility when it comes to the conformers.

however from a usability standpoint,  including the UI that you have shown above it might be better to add target in a similar manner to how families are implemented.

that way it would still be the responsibility of the `def process` to implement where it goes but it would be possible to generate a UI based on the plug-in which would have the information available.

the question is the following, Do we want to have targets being a single selection as the UI example suggests? or do we want to have the flexibility to add multiple and have the processor work on all of them?

**Comment by mottosso** [comment]
> The method currently implemented would allow for more flexibility when it comes to the conformers.

Then let's start with that. At least there is the option to add the extra behaviour should it become necessary and more intuitive, whereas it would have been more difficult to remove it later if were to add it right away.

> the question is the following, Do we want to have targets being a single selection as the UI example suggests? or do we want to have the flexibility to add multiple and have the processor work on all of them? 

I suppose the dropdown could have checkboxes for each target, but I wonder what options should be available, and should they all be toggled per default?

For example, if one registers three targets, should they each be toggled, and then be optionally de-toggled, or should only the last target be toggled, leaving the others optional?

We need use cases to find this out I think.

Perhaps once you have a few plug-ins using this feature could we return to this topic to discuss how to best implement it graphically. For the time being, we can assume they are all toggled, but invisible in the gui. Functionally it seems to work well.

Thoughts?

**Comment by larsbijl** [comment]
I agreement we need to have a use case before we can move further as to how we want to visualise it.  I can see the following 2 scenarios as being useful.

1) We add a targets attribute to the plug-in interface,  its the developer's responsibility to add targets to the plug-in and all of them would be run at the same time.  however there was be no different than just generating multiple outputs in the `process`

2) the user can define which target is active, only plug-ins that have that target will be active to run.

**Comment by mottosso** [comment]
Cool, I'll merge #258 so we can start using it and think about where to go from there.
