### ISSUE TITLE
Plug-in filepath can't be retrieved

### ISSUE THREAD

**Issue by BigRoy** [pyblish/pyblish-base#229]
Plug-ins are currently loaded using `execfile()` making it (close to?) impossible to retrieve the original source file of the plug-in. More information: http://stackoverflow.com/questions/17470193/python-metaclass-execfile-inspect-globals-namespace

I'd opt to store it on the plug-in. 
Briefly chatted with Marcus and thinking about using `__path__`.

That way the plug-in source path can be retrieved for all loaded plug-ins like:

``` python
import pyblish.api

for plugin in pyblish.api.discover():
    path = plugin.__path__
```

**Comment by mottosso** [comment]
Wondering whether it would be possible for a plug-in to add the path to it's parent module directly instead?

``` python
class MyPlugin(...):
  __path__ = get_path_to_parent_module()
```

It would be better, as it would mean the variable would be available even when it isn't coming from `discover()`. But I'm not sure it's possible.

**Comment by BigRoy** [comment]
Good point. 

Another issue putting it in `discover()` might be handling the memory registered plug-ins and whether we set the `__path__` attribute there.

> Wondering whether it would be possible for a plug-in to add the path to it's parent module directly instead?

Could be done in `__new__()` maybe?

**Comment by mottosso** [comment]
> Could be done in `__new__()` maybe?

Plug-ins aren't instantiated, but you could get the same affect via the metaplugin. It's triggered as soon as the file is read.

> Another issue putting it in discover() might be handling the memory registered plug-ins and whether we set the `__path__` attribute there.

A `__path__` of `None` for in memory plug-ins sounds logical to me. What do you think?

**Comment by BigRoy** [comment]
> A **path** of None for in memory plug-ins sounds logical to me. What do you think?

Yup. +1

**Comment by BigRoy** [comment]
I've tried changing the metaclass used by plugins to something like:

``` python
class MetaPlugin(type):
    """Rewrite plug-ins written prior to 1.1

    ..warning:: In case of plug-ins written prior to 1.1,
        that also process both instance and context,
        only the instance process will remain available.

    """

    def __init__(cls, *args, **kwargs):

        append_logger(cls)
        evaluate_pre11(cls)
        evaluate_enabledness(cls)

        # Store the path of this plug-in on the class
        cls.__path__ = None
        if cls.__module__ != '__main__': # if not local (in-memory)
            try:
                cls.__path__ = inspect.getfile(cls)
            except RuntimeError, e:
                print e

        return super(MetaPlugin, cls).__init__(*args, **kwargs)
```

Unfortunately this will lead to the plug-ins path being defined to the file with the RPC (eg. `Pyblish\lib\pyblish-x\modules\pyblish-rpc\pyblish_rpc\mocking.pyc`)

A possible workaround is to perform a lookup in the initialization for a global variable like `_execfile_plugin_path` that is passed as a global value to `execfile()`.

For example:

``` python
class MetaPlugin(type):
    """Rewrite plug-ins written prior to 1.1

    ..warning:: In case of plug-ins written prior to 1.1,
        that also process both instance and context,
        only the instance process will remain available.

    """

    def __init__(cls, *args, **kwargs):

        append_logger(cls)
        evaluate_pre11(cls)
        evaluate_enabledness(cls)

        # Store the path of this plug-in on the class
        cls.__path__ = None
        if cls.__module__ != '__main__': # if not local (in-memory)
            if '_execfile_plugin_path' in globals():
                global _execfile_plugin_path
                cls.__path__ = _execfile_plugin_path
            else:
                try:
                    cls.__path__ = inspect.getfile(cls)
                except RuntimeError, e:
                    pass

        return super(MetaPlugin, cls).__init__(*args, **kwargs)
```

**Comment by BigRoy** [comment]
Wait, did you just nail that?

**Comment by mottosso** [comment]
Ok, I emulated the import mechanism and now `inspect.getfile()` and `sys.modules[]` seems to work correctly.
