### ISSUE TITLE
'Pyblish' package on PyPi is actually pyblish-base

### ISSUE THREAD

**Issue by jedfrechette** [pyblish/pyblish-base#249]
https://pypi.python.org/pypi/pyblish

It looks like the package page on PyPi hasn't been updated to reflect the project restructuring in version 1.3.

**Comment by mottosso** [comment]
This is intentional.
- http://forums.pyblish.com/t/renovation-taking-place-today/191

I added the notes to the release notes just now (bottom):
- http://forums.pyblish.com/t/pyblish-1-3-released/193

Pyblish will only ever be available on PyPI in this form; never including binaries or additional projects.

**Comment by jedfrechette** [comment]
So:

`pip install pyblish`

get's me something different than:

`git clone pyblish`

or

`pyblish-*-setup.exe`

Doesn't this just move all of the problems I presented in pyblish/pyblish-win/issues/10 to a different place?

Rereading the renovation notes again I'm still confused about how package versions are supposed to be handled. Are all of the `pyblish-*` submodules intended to have the same version as `pyblish`? I don't think that's what you want, but what happens when `pyblish-base` is still at 1.x, while `pyblish` is at 1.x+1 because its readme was updated? In that situation, what's the version number of "Pyblish" on PyPi? It still seems like calling different things by the same name is a bad idea.

To give a concrete example, my app currently depends on `pyblish=1.2` (but none of the other pyblish-\* modules). I can install my app with pip and it will pull in pyblish from PyPi if needed. With 1.3 I don't need to change my setup.py (that's nice), but since now I'm really depending on `pyblish-base` behind the scenes, I need to have a 5 minute talk with any new developers I bring on explaining how `pyblish` is only sometimes pyblish. Similarly, as an end user if I do `pip install pyblish` I'm probably expecting to get all of the sub packages, not just `pyblish-base`

Couldn't backwards compatibility be maintained in a more straightforward way by always referring to `pyblish-base` as `pyblish-base` while having the `pyblish` module essentially do:

`import pyblish-base as pyblish`

That's what most users would want, while allowing all of the packages to be independent and preventing the sort of conceptual namespace clash  that still exists.

**Comment by mottosso** [comment]
> Are all of the pyblish-\* submodules intended to have the same version as pyblish?

Not quite; `publish` still versions independently; only `pyblish-win` inherits it's version from `pyblish`.

I made a little graph to illustrate.

``` bash

                                  +----------------+
                                  |                |
                                  |  pyblish-win   | inherits 1.3.1
                                  |                | from pyblish
                                  +----------------+
                                          |
                                          |
                                          |
                                          |
                                  +-------v--------+
                                  |                |
             +--------------------+     pyblish    +------------------------+
             |                 +--+                +---+                    |
             |                 |  +----------------+   |                    |
             |                 |        1.3.1          |                    |
             |                 |                       |                    |
             |                 |                       |                    |
             |                 |                       |                    |
    +--------v-------+   +-----v----------+   +--------v-------+   +--------v-------+
    |                |   |                |   |                |   |                |
    |  pyblish-base  |   |  pyblish-qml   |   |  pyblish-rpc   |   |  pyblish-maya  |
    |                |   |                |   |                |   |                |
    +----------------+   +----------------+   +----------------+   +----------------+
          1.3.0                 0.4.0                0.2.0                1.2.0


```

We've effectively peeled off one layer of versioning; the one originally made independently in `pyblish-win`. Which means that now when you refer to 1.3.1 of pyblish, you would be referring to the same version on any platform and regardless of whether you installed via the Windows installed or pulled repositories on your own.

I think this was a great improvement, and I have you to thank for it!

But I'm sorry to see you still find it confusing; would it help to take PyPI out of the equation?

You are equally welcome to `pip install` via git directly if that helps your fellow developers.

``` bash
$ pip install git+https://github.com/pyblish/pyblish-base
```

> That's what most users would want, while allowing all of the packages to be independent and preventing the sort of conceptual namespace clash that still exists.

I suppose I see things a little differently. To me, `import pyblish` is the Python interface to Pyblish _the framework_; not of any particular GitHub or Git repository. Those are more like "vessels" in which Pyblish can safely be transported and maintained. These means of transportation may change, but the interface does (i.e. should) not.

Let me know your thoughts on this.

**Comment by jedfrechette** [comment]
> would it help to take PyPI out of the equation?

Yes, I think PyPI is currently the only place that doesn't match the schema you've outlined in the above graph. I think the new layout makes a lot of sense, btw.

If you want to distribute Pyblish as a package on PyPI I think it should provide everything, e.g. pyblish-base, pyblish-qml, pyblish-rpc... On the other hand if you just want to distribute pyblish-base via PyPI then the package should be called pyblish-base. I think the only problem right now is that you're distributing pyblish-base, but calling it pyblish.

It seems like the ideal situation would be to have separate PyPI packages for each of the submodules (pyblish-base, pyblish-qml, etc.) plus a top level pyblish metapackage that depends on all of them. That would allow users to easily to pull in either the entire stack or just the components they need depending on their requirements.

**Comment by mottosso** [comment]
> If you want to distribute Pyblish as a package on PyPI

This really has roots from early on in the project, when all projects were in fact distributed in this way and the goal was to stick with it.

But issues arose once packages became more complex and more customisability was needed; primarily related to network installs. So most packages were removed from PyPI and a custom distribution method was developed; pyblish-suite (former pyblish-x) followed by pyblish-win where we conquered the hassle involved in everyone compiling PyQt5 on their own and where versions got together into a supported combination, such that we wouldn't have to support the infinitely large combination of versions one could potentially end up with when installing each project separately.

So perhaps the time has come to strip PyPI of pyblish-base as well and stick with a single distribution mechanism; GitHub.

Personally, I don't see a problem with having `pyblish-base` be `pyblish` on PyPI; to me it's the PyPI package name, and not necessarily in any way related to Git or GitHub project name. Similar to how PyQt goes by the name `python-qt5` on some package managers, and `python-pyqt` or `python3-pyqt5` on others. It's a name local to the distribution platform.

Beyond that, renaming it might move the problem to how you `import pyblish` where you might instead start to expect `import pyblish_base`. But then that moves the problem further over to the question "Should the Python interface to Pyblish the framework be called pyblish_base?" And why "base"? Answering that would involve getting into the internals of how Pyblish is organised on GitHub which I'm not sure is relevant to the end-user.

**Comment by jedfrechette** [comment]
>  I don't see a problem with having pyblish-base be pyblish on PyPI

I think users will be surprised and disappointed when they install "Pyblish" from PyPI, then can't do `import pyblish_qml` like they can if they install Pyblish in any other manner. I think this is a branding more than technical issue. When users see Pyblish they should think of the entire suite and all of the goodies that come with it.

> So perhaps the time has come to strip PyPI of pyblish-base as well and stick with a single distribution mechanism; GitHub.

That would return consistency but is it any easier than just renaming the PyPI package to pyblish-base? I think there is a lot of value to keeping at least part of Pyblish on PyPI. Honestly, I'd love to see the whole suite back on PyPI, but that's another discussion.

> renaming it might move the problem to how you import pyblish where you might instead start to expect import pyblish_base.

What if users who want to keep dependencies small and use `pyblish-base` directly needed to do `import pyblish_base`. While the typical user would still install the `pyblish` package that continues to provide the same interface via `import pyblish.api`, just like it does now. That way only code using `pyblish-base` directly would need to be updated. The `pyblish` package could also be extended to provide similar aliases for the other sub packages. For example, it could provide `import pyblishi.qml`, which would be equivalent to `import pyblish_qml`. As a bonus this might make the API a little more discoverable.

**Comment by mottosso** [comment]
> For example, it could provide import pyblishi.qml

Namespace packages did look lucrative at first and we did consider them.
- https://github.com/pyblish/pyblish-base/issues/56

> I think users will be surprised and disappointed when they install "Pyblish" from PyPI, then can't do import pyblish_qml like they can if they install Pyblish in any other manner.

I think it sounds like a couple of focus groups are in order. I'll have a look at arranging this and perhaps we can get a glimpse of what users actually think, before we go deeper into speculations and change things that might already be what they want.

**Comment by mottosso** [comment]
pyblish-base is now pyblish-base on PyPI.

``` bash
$ pip install pyblish-base
```

`pip install pyblish` currently also pyblish-base, but will transition into the combined version of all projects next.
