### ISSUE TITLE
Nothing Injected to Process

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-base#259]
No warnings are issued if you inject a plugins `process` method with nothing.

``` python
class ValidateContext(pyblish.api.Validator):
    families = ["A", "B"]

    def process_context(self):
        self.log.info("Processing context..")
```

This results in the plugin not processing correctly and not showing up in the GUI.

**Comment by BigRoy** [comment]
Just to be sure. Is that example code actually valid? Does `process_context()` exist? And if it does, does it exist without arguments?

Shouldn't it be `process()`?

**Comment by mottosso** [comment]
It's good that you are on alert. But this is actually ok; pre-1.1 plug-ins are implicitly rewritten to post-1.1.
- [See here](https://github.com/pyblish/pyblish-base/blob/62d767f4386d33e7cb18f544086ac128af02c1bc/pyblish/plugin.py#L111)

In practice, this plug-in is identical to one with `process()`.
