### ISSUE TITLE
pyblish.util.publish() ignores instance "publish" state.

### ISSUE THREAD

**Issue by BigRoy** [pyblish/pyblish-base#282]
# Problem

The `publish` state of an instance is not used in `pyblish.util.publish()`. As such even when False it will process those instances.
# Solution

See [gitter discussion](https://gitter.im/pyblish/pyblish?at=577a8cd14fd381610991f991)

This:

``` python
    # Second pass, the remainder
    for Plugin, instance in logic.Iterator(plugins, context):
        state["nextOrder"] = Plugin.order
        ...
```

Should become:

``` python
    # Second pass, the remainder
    for Plugin, instance in logic.Iterator(plugins, context):
        if not instance.data.get("publish", True):
            continue

        state["nextOrder"] = Plugin.order
```

**Comment by mottosso** [comment]
We could have a look at how Lite or QML does it.

``` python
        for plug, instance in pyblish.logic.Iterator(plugins, context):
            if not plug.active:
                continue

            if instance is not None and instance.data.get("publish") is False:
                continue
```
- [pyblish-lite.control.py](https://github.com/pyblish/pyblish-lite/blob/3538a2fbe9191357ce72da2e5d4ff5dc5441c62a/pyblish_lite/control.py#L228)

There we have it!

**Comment by mottosso** [comment]
Implemented.
