### ISSUE TITLE
Verbose output from publish

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-base#304]
**Goal**

To get more verbose output from ```pyblish.util.publish()```

**Motivation**

Currently using ```pyblish.util.publish()``` does not produce any print statements, and so it's left to the developer to parse the results from ```context.data["results"]```.

**Suggested implementation**

Would be good to by default output log messages, as this is more intuitive for a new developer and easier for existing developers.
So a suggested interface to the publish method would be to add a keyword argument, so if the verbose output is not desired, it can be turned off; ```pyblish.util.publish(silent=True)```.

**Comment by mottosso** [comment]
Simple enough, the `publish()` function always runs till the end so looping through the results at the point should give you the effect you are looking for.
- [End of function](https://github.com/pyblish/pyblish-base/blob/764583bfb79dd55a6f67c513d819306ec57a635a/pyblish/util.py#L92)

**Example**

``` python
for result in context.data["results"]:
  for record in result["records"]:
    print(record.msg)
```

The members of each `record` are these:
- https://docs.python.org/2/library/logging.html#logging.LogRecord

**Comment by tokejepsen** [comment]
Is this a duplicate issue of https://github.com/pyblish/pyblish-base/issues/299 ?

**Comment by mottosso** [comment]
> Is this a duplicate issue of #299 ?

Yes, I do think so.
