### ISSUE TITLE
Installing and Configuring

### ISSUE THREAD

**Issue by ljkart** [pyblish/pyblish-base#31]
Would like discuss about tool installation and configuration

Installation can be using pip or by any other way?.

`pip install publish`

I would like to keep a Publish configuration directory somewhere in the disk, by having a folder structure where we can keep all associated files and folders. e.g.:

``` bash
/Publish
  /Projects
     /my_project
        /app_01
        /app_02
        /global
    /global
```

Thoughts?

**Comment by mottosso** [comment]
Do you mean that each project under `/Publish/Projects` would be looked up against projects in a studio?

Like, if we're running `Spiderman`, it would look for `Spiderman` within the `/Publish/Projects` folder for its configuration?

**Comment by ljkart** [comment]
right..! that can be set as a $ROOT environment variable for our tool to understand.

**Comment by mottosso** [comment]
Sure, we could try that. Would you like to have a look at implementing this?

**Comment by mottosso** [comment]
As for installation; `pip` would be ideal in my opinion, although I'm foreseeing some issues with that down the line, mainly related to Qt.

**Comment by mottosso** [comment]
As far as I know, pip doesn't do PyQt nor PySide without also requiring users to install the Qt binaries, but my hope is that we'll go beyond that into PyQt5 to eventually work with QML.

There are workarounds; we could request that users installs these separately, but for now this isn't an issue as everything is running from within Maya during which we'll probably stick to its bundled PySide unless someone has any other preference.

**Comment by ljkart** [comment]
this pip search pyqt result, it is listing pyqt4
![pip_pyq_resultt](https://cloud.githubusercontent.com/assets/6689658/3859385/0f6cf7e2-1f18-11e4-88e0-b4587ebab9d0.jpg)

or we can PyQt4 in the "Requrement" section of Publish tool.

**Comment by achayan** [comment]
Are you sure that we need to keep projects configs under single structure ?. I think only project initial config like project path will will be under publish structure and other all project based configs will go under each project...

**Comment by ljkart** [comment]
Then where will be that project config?

**Comment by mottosso** [comment]
@ljkart, perhaps if you could give an illustration of where such a file would be located along with what you are thinking of storing within it, it might be clearer what type of config you are referring to and where it may be best suited to go.

**Comment by mottosso** [comment]
How about something like this:

``` bash
/path/to/my/plugins/validate_personal_settings.py
                   /validate_something_else.py
```

If this is the path to some custom plugins, like validators and selectors, then we could have Publish look for an environment variable, similar to PYTHONPATH:

``` bash
PUBLISHPLUGINPATH=/path/to/my/validators
```

This way, per-project plugins could look like this:

``` bash
PUBLISHPLUGINPATH=/projects/spiderman/publish/plugins;/my/personal/plugins
```

Which could get setup together with other environment variables during startup.

Personally, I'm not a fan of environment variables, but it's a proven method that works.

Alternatively, plugins could get specified in the start-up script of Publish:

``` python
publish.show(paths=["/projects/spiderman/publish/plugins"])
publish.publish_all(paths=["/projects/spiderman/publish/plugins"])
```

Thoughts?

**Comment by mottosso** [comment]
I was thinking, that when installing Publish, its integration into various hosts should be installed automatically. Such as, the menu-item for Maya and Nuke, or shelf-button for Houdini or however else we choose to integrate it.

At the moment, I've assumed that users append the `publish/integration/maya` directory to their PYTHONPATH which would make the contained `userSetup.py` visible to Maya and thus have it automatically run.

But, this is only a temporary solution as it wouldn't work with other hosts, and modifying one's PYTHONPATH isn't, in my opinion, very installer friendly.

So we'll need to come up with a better way. One method may be to look for an existing `userSetup.py` and append Publish to it.

``` python
>>> # E.g.
>>> usersetup = r'c:\users\{user}\Documents\maya\scripts\userSetup.py'
>>> if os.path.exists(usersetup):
...      with open(usersetup, 'a') as f:
...      f.write('\nimport publish\npublish.integrate()')
```

But when it comes time for other hosts, I'm not sure this is as viable. Does Nuke or Mari provide such hooks? And what about when hosts aren't installed where you'd expect them to be, such as on the various Linux platforms?

**Comment by tokejepsen** [comment]
Nuke has `menu.py` instead of `userSetup.py`.

I wouldn't disregard environment paths entirely, as they are quite useful when going into other apps. But dont think we'll get a workflow down until we start working with other apps. Also wrapping apps executables for setting environment variables are quite common.

**Comment by mottosso** [comment]
> I wouldn't disregard environment paths entirely

No, I'm with you on that. This would be the simplest case scenario; I'd expect serious studios to integrate Publish, either by modifying environment variables by hand or via a bootstrapper/wrapper like you mention.

For our initial users however, this will probably be less common. At least until they know they like it and can use it. For them, I'd like Publish to install as smoothly as possible so that we can first convince them that Publish rocks. Only then would I expect them to take greater leaps and try harder.

**Comment by tokejepsen** [comment]
> For our initial users however, this will probably be less common. At least until they know they like it and can use it. For them, I'd like Publish to install as smoothly as possible so that we can first convince them that Publish rocks. Only then would I expect them to take greater leaps and try harder.

True, but wouldn't we just take care of the environment variables for them on install?

**Comment by mottosso** [comment]
Oh, sorry I thought that's what we meant. Basically:
1. This will install publish, and automatically integrate (append to the file-menu)
   
   ``` bash
   $ pip install pypublish
   ```
2. And for those who need greater integration, we could keep the door open for adding `integration/maya` to their PYTHONPATH via their bootstrapper/wrapper.

The issue lies in how much integration the installation can do on its own.

**Comment by mottosso** [comment]
Feel free to re-open this if something is unclear!
