### ISSUE TITLE
Modifying Plugin Flow Configuration

### ISSUE THREAD

**Issue by iwootten** [pyblish/pyblish-base#316]
As a developer, I'd like more control over the flow of pyblish plugins, so that I can better use and customise plugins shared with me.

This would be a greater level of control than that which a simple list of directories set by the environment variable.

This seems to be a common theme with the work @tokejepsen and I are sharing - I'd like the ability to include some plugins, ignore others for instance. Basically a way of configuring the complete plugin flow myself. I could go ahead and register each plugin individually, but then having an official solution as part of pyblish would be my preferred option.

One solution could be a configuration file which specifies the order and plugins to use for particular scenarios. That scenario could be triggered when a given event happens - for instance a maya publish.

**Comment by mottosso** [comment]
Thanks @iwootten.

The general idea is to not let configuration determine flow, but data. Of having all plug-ins on your path at all times, and let the data determine flow based on the kind of data it is and what attributes it has.

But there is room for additional customisation, and in this case it sounds like files and paths might not be the best approach for you.

Let me know what you think about this.

**my_plugins.py**

```python
from pyblish import api

class CollectThings(api.ContextPlugin):
  ...

class ValidateThings(api.InstancePlugin):
  ...

class ExtractThings(api.InstancePlugin):
  ...
```

**your_configuration.py**

That is, don't let files host plug-ins, let a Python module handle it. Then you can register individual plug-ins explicitly.

```python
import my_pipeline
from pyblish import api
from my_plugins import CollectThings, ValidateThings, ExtractThings

api.register_plugin(CollectThings)
api.register_plugin(ValidateThings)

if my_pipeline.some_condition is True:
  api.register_plugin(ExtractThings)
```

**Comment by iwootten** [comment]
That seems like it might work for me. Wouldn't this approach also work for #306?

**Comment by mottosso** [comment]
> Wouldn't this approach also work for #306?

Yes, it would side-step the issue. It wouldn't need to consider modules as you take on that responsibility. But it also means you are in charge of reloading your plug-ins.

**Comment by hannesdelbeke** [comment]
the new filter mechanic in pyblish allows you to select which plugins you want to use. to modify your flow
getting started docs regarding filtering: https://learn.pyblish.com/24-filtering

I created a tool on top of this to control workflows with json files: https://github.com/hannesdelbeke/pyblish-plugin-manager

avalon also has a similar setup https://github.com/pypeclub/OpenPype/blob/1e7378c80fa027b49d06cd38967c8e6dbcdf5818/openpype/lib/plugin_tools.py#L207-L264
