### ISSUE TITLE
Stage 3 - Hack and slash

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-base#32]
What do you guys think about moving on from _Requirements gathering_ to getting Publish _up and running_?

https://github.com/abstractfactory/publish/wiki/development-status

It doesn't mean we won't find new requirements or won't be able to come up with new ideas, just that the ones we've currently got are sufficient in getting us off the ground and into writing some code!

My suggestion is for us to get a working copy up and running, with enough room for individual contribution, and to keep it running from now on. As in, at any point should anyone be free to grab a clean copy of our repository and start using it, regardless of what's happening behind the scene. 

The target audience at this point is _us_ and not necessarily any real users, with the goal of each of us being able to experiment with new ideas with working code and to directly contribute value whilst ensuring that changes doesn't eliminate or break any currently working feature.

I think we're ready! Let me know what you guys think!

Best,
Marcus

**Comment by ljkart** [comment]
We need to summarize all the issues we came across before we start, at least all progress till now,  can you do that?

**Comment by mottosso** [comment]
Good point, I'll see what I can do.

## Stage 3 - Hack and Slash

Hack and Slash is _not_ about perfection nor usability; but about minimalism. About getting the least amount of features required for a publish to take place. At this point, this involves;
1. A method for users to select what to publish
2. A method for users to configure their publish
3. A method for users to trigger a publish from within Autodesk Maya
4. An output directory

Selection doesn't have to be complete, nor configuration. The trigger doesn't have to be final, only _available_ and the output directory does not have to be accurate.

Once up and running, we'll be able to clearly visualise our proposals and ideas by either altering or augmenting this behaviour. The key thing is to try and not break the interface towards the user; the interface in this case is steps 1-3.

Edit: and 4 of course, if we work with templates/conform!

We can still do it, of course, and we most likely will. But we should strive to _add_ and avoid _change_ as much as possible. 

## Example

Selection could be a single function that looks for objectSets. Now, we've talked about whether objectSets were a good idea or not so if we were to want to introduce an alternative, we could, as long as it also works with sets.

Makes sense?

## Goal

At the end of the day, we're looking to enable contributors to contribute whilst worrying as little as possible that their contributions will break other contributions. This type of workflow will complicate development for each and every one of us, but the sum of our efforts should greatly increase in the long run.

At least, that is my hope!

**Comment by ljkart** [comment]
Sounds good! we can start by having this in mind and having a list of all the points we shared will be helpful to every one to start from same point and experiment different ideas.

**Comment by mottosso** [comment]
I'd like to propose a working copy that I pushed only a few minutes ago and that lives up to the above requirements.

## How to use

End-users should eventually install via pip, but developers must pull from this repo.
1. Once pulled, add the repo to your PYTHONPATH
   - e.g. `PYTHONPATH=c:\users\marcus\GitHub\publish`
2. Also add the [_integration/maya_](https://github.com/abstractfactory/publish/tree/master/publish/integration/maya) directory.
   - e.g. `PYTHONPATH=c:\users\marcus\GitHub\publish\integration\maya`
   - The [userSetup.py](https://github.com/abstractfactory/publish/tree/master/publish/integration/maya/userSetup.py) therein will append an item to the File-menu of Maya. This triggers `publish.main.publish_all()`
3. Open [the test](https://github.com/abstractfactory/publish/blob/master/resources/tests/selection/multiple_selection_test/maya/scenes/v001.ma)
4. Hit File `>>` Publish

I'm imagining this workflow to always work and for other features to append to it rather than change it; e.g. eventually inserting a GUI in-between clicking and publishing. Let's talk about the pros and cons of that.

I've also reserved space on PyPI for our project.
- https://pypi.python.org/pypi/pyPublish/0.1.4

You can `pip install pypublish`, but some files are missing, preventing it from working properly. This is something we'll have a look at, but for now it isn't meant for non-developers anyway.

Once you've gotten the [test scene](https://github.com/abstractfactory/publish/blob/master/resources/tests/selection/multiple_selection_test/maya/scenes/v001.ma) to publish successfully, try and understand what is going on. Implement a validator using the same family and put it in along with [the other validators](https://github.com/abstractfactory/publish/tree/master/publish/validators) to see it run. Have a look at the existing validators for guidance.

One of the validators ensure that there are no muted channels in the scene. If you key the mesh and mute its channel, you'll note that it won't publish. The same goes for the naming convention. Change its name and see it fail. Have a look at [the validator](https://github.com/abstractfactory/publish/blob/master/publish/validators/validate_naming_convention.py#L25) for how it works.

Or, alter the family from _model_ to something else and implement a validator for your unique family.

## Where to go..

At this point, most of the behaviour is embedded into [main.py](https://github.com/abstractfactory/publish/blob/master/publish/main.py) but I'd imagine this to be broken apart  into separate modules as we go along. For example, to work with selection or extraction in isolation. We'll discuss a proper interface/internal-API for ourselves for these to remain as independent as possible.

About validations, they are currently running upon the Plug-in system [as described here](https://github.com/abstractfactory/publish/wiki/plugin-system). In a nutshell, they work like this:
1. A publishable instance is selected in the scene
2. The instance is tagged with "model" or any other [family](https://github.com/abstractfactory/publish/wiki/family)
3. Upon validation, plugins are looked up according to which family they are written for
4. Matches are run upon each outgoing instance

We've spoken about having a more graph-like structure to this and other [_Filters_](https://github.com/abstractfactory/publish/wiki/object-model), now is a good time to get into that and see how that would work.

@bigroy, your core.py was renamed [abstract.py](https://github.com/abstractfactory/publish/blob/master/publish/abstract.py) to more precisely identify its contents.

## Todo

Many things are missing, some of which are:
1. We haven't properly talked yet about metadata, what to extract and where to write it.
2. The only modular part of the system so far is validations; selections, extractions and conforms are up next
3. There is no GUI
4. There are no configuration per-project, as discussed [here](https://github.com/abstractfactory/publish/issues/31)

## Tests

At the moment, tests must be run via mayapy as opposed to the standalone Python. This is something I'd like to change eventually, hence [publish.mock](https://github.com/abstractfactory/publish/blob/master/publish/mock), but until then, tests are run via the bundled package "nose" like this:

``` bash
$ cd path/to/publish
$ path/to/mayapy -m publish.vendor.nose --verbose --with-doctest --exclude=nose
```

Which means: "using Maya's mayapy.exe (if on Windows), run the module _publish.vendor.nose_ using these arguments."

I recommend that you run these tests whenever you make a change. The goal if for these tests to catch anything that breaks, so whenever a new feature is added, a test must be added to test that it works for the next person who will change things. Down the line, I'll suggest we enter into a Test-driven development style, but until we have something more substantial to test against I think its best we cross that bridge when we get to it. Nevertheless, I recommend that you always include tests with your changes.

Looking forward to hearing what you think, and remember, all of this is open for discussion and we're still experimenting and finding alternatives and ways to make things better.

Best,
Marcus

## FAQ

> Do I select, and hit publish?

No need to select, selection is already stored in the scene. Have a look at `publish_model_SEL` for details. It will contain two attributes; `publishable` and `family`. Family is used in determining which validators to run.

> Where does the publish go?

Once published, have a look in the script editor for details.

> If I rename `Peter_AST` to `Peter_AT`, will I have to save the scene before I can publish?

No, its only dependency is that the scene is saved at all. Otherwise, publishes will end up in your default project directory; e.g. your home directory.

**Comment by mottosso** [comment]
Hi again folks,

A little check-up on how things feel with the current version. How does it feel? Is it difficult to wrap your head around and get started with coming up with ideas and contributing code? My goal for for all of you to feel perfectly confident in submitting ideas and code, so if there's anything you feel is tricky at the moment, do speak up so we can find the best way of working together; remember, this project is nothing without you!

Off the top of my head, here are some things I feel could be improved for you to feel more comfortable, feel free to chip in with areas I may be missing out on.

### Separate code into individual modules

If code were better separated, you could more safely alter things without breaking the full program. It may also make it more easy to digest and understand, but at the same time make it more difficult to get an overview of how it runs.

### Provide basic tutorials

Tutorials would of course be temporary, as we'll be changing most of everything as we go. But if it helps getting you up and running, I'd be happy to provide some and to try and keep them updated as we go along.
1. [Installation](https://github.com/abstractfactory/publish/wiki/installing)
2. [Publishing your first scene](https://github.com/abstractfactory/publish/wiki/publishing-your-first-scene)
3. [Creating your first plugin](https://github.com/abstractfactory/publish/wiki/creating-your-first-plugin)

### Chat

If you'd like, we could all get together in a group-chat on Google Hangouts and get to know each other a little. I know many of you are using Hangouts, but if any of you aren't and would still like to join, speak up here and we'll get things sorted out for you.

If you have any other thoughts or questions, ask away right here and I'll do my best to help you out!

Yours truly,
Marcus :)

**Comment by mottosso** [comment]
It has come to my attention that the current state of code in this repository is quite difficult to understand. So I put together a little walkthrough of what is inside of this repo so as to better understand what is going on.

### [Walkthrough](https://github.com/abstractfactory/publish/wiki/quickstart)

If you can think of anything else that might help newcomers get started, say something here!

Best,
Marcus

**Comment by tokejepsen** [comment]
some thoughts on going through publish...

config.json:
- this might be changed in the future as the templating system get impletemented, but "prefix" seem odd for a directory

domain.py:
- is this not redundant? Seems like an extra layer to me.

plugins module:
- as for programming terms, this makes sense as that is what all the modules within are. But I would suggest having a Validators, Extractors etc, modules, instead of prefixing the modules with the category.

**Comment by mottosso** [comment]
> config.json: .. but "prefix" seem odd for a directory

Agreed, couldn't think of a more suitable name, as it could also mean several subdirectories, or an absolute path, e.g.:

``` json
{"prefix": "/mnt/projects/all_publishes"}
```

Or

``` json
{"prefix": "sub/folder/published"}
```

What alternatives do you have in mind?

> domain.py: is this not redundant? Seems like an extra layer to me.

Agreed, the only reason I separated implementations from abstract base-classes into their own module was because abstract base-classes can't (or shouldn't) be instantiated directly. So by putting them in their own module, their intent could remain clear. But, at the moment they do nothing and most certainly look redundant.

One option provided by @BigRoy was, instead of having `abstract.py` and `domain.py`, to put them all within a `core.py`. But personally, I think "core" is just a fancy name for "misc", as in "I'm not sure what to call it, but it's important". Sorry, Roy. :)

I'd be happy to hear about alternatives.

> But I would suggest having a Validators, Extractors, modules, instead of prefixing the modules with the category.

Did you mean individual subdirectories per type of filter? E.g.

``` bash
publish/
  plugins/
    validators/
      my_validator.py
    extractors/
      my_extractor.py
```

Otherwise, it sounds like your describing how things are at the moment, individual modules! :)

**Comment by tokejepsen** [comment]
> What alternatives do you have in mind?

I would go with "directory", think it says it all.

> I'd be happy to hear about alternatives.

`core.py` sound good to me, but ill have a think about it.

> Did you mean individual subdirectories per type of filter?

Yup, subdirectories. We could, if we dont look at the inheritance, use the submodules for the plugin module to discover the category of the plugin.

**Comment by mottosso** [comment]
> We could, if we dont look at the inheritance, use the submodules for the plugin module to discover the category of the plugin.

Do you mean the parent package of a module? (i.e. "super-package")

``` bash
# E.g.
validators/
   __init__.py    <- this makes it a package
   my_plugin.py   <- This is a validator, because it is within the validators package
```

Personally, I find that it may make plug-ins less self-contained and thus less share-able. It would potentially also produce directories with quite a few plugins, and some with only one or two.

``` bash
# E.g.
validators/
    lots.py
    and_lots.py
    ...
selectors/
    my_only_selector.py
```

How come you don't like the prefix-approach? It's proven to work quite well with tests, both the built-in unittest uses this, and nose too. I thought it would be nice to align with at least some conventions.

**Comment by tokejepsen** [comment]
Now that you mention it, having multiple directories might not be good if people are going to use environment variables to add them. Then its better to have just the one directory to discover plugins within.

Prefix-approach just seems to restrict the filenames, and they become long pretty fast. Dont have other issues with it other than, I dont like being told what to name my files:)
I know next to nothing about unittest or nose, so I cant give an alternative or better solution.

**Comment by mottosso** [comment]
@tokejepsen would you like to continue the selection implementation? I'll move on with separating Maya from main.py.

**Comment by tokejepsen** [comment]
@mottosso, sure, though I'm not entirely sure what needs to be done apart from continued testing and writing different selectors?

**Comment by mottosso** [comment]
Wasn't there the thing about making sure to select _all_ nodes within selected instances? Where did we talk about that?

**Comment by tokejepsen** [comment]
was in #40:)

Yeah, I'll have a look at the transform selector.

**Comment by mottosso** [comment]
Ah, that's the one. :)

**Comment by tokejepsen** [comment]
> How come you don't like the prefix-approach?

Just thought of another reason; you would most likely prefix your validators/extractors with the host name to organize. If you have prefix of the category, then your names become long quite fast.

**Comment by mottosso** [comment]
You really don't like long names, huh? :)

That would certainly be one way of doing it, although for Maya-specific plugins, I'd probably tend to add those via the userSetup.py of that particular host.

``` python
# userSetup.py
import os
os.environ['PUBLISHPLUGINPATH'].append('/maya/specific/plugins')
```

I think that, as long as the functionality is what we'd like it to be, the particular manner in which we do it is less important. I'd be happy to give your suggestion a go so feel free to make it a pull-request.

**Comment by mottosso** [comment]
Closing this as we are in the middle of it.
