### ISSUE TITLE
Implement __hosts__ attribute

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-base#36]
Need a `__hosts__` attribute on plugins, to distingush between valid DCC hosts.

**Comment by mottosso** [comment]
Having a look at this now.

**Comment by mottosso** [comment]
About the prefix and suffix double underscores, I'm thinking of having these removed as they look plain ugly. Is anyone aware of any reason why these should exists? To me, the indicate a built-in method, such as `__init__` or `__str__`, as opposed to a user-added property.

``` python
# For example
class Filter(object):
    families = []
    hosts = []
    version = (0, 0, 0)
```

**Comment by tokejepsen** [comment]
Got no problem with that:)
