### ISSUE TITLE
Vendor libraries injected in sys.path are messing up environment

### ISSUE THREAD

**Issue by buddly27** [pyblish/pyblish-base#365]
Is this line absolutely necessary?

https://github.com/pyblish/pyblish-base/blob/841f40821507964389adac01683ac86f745bb5fe/pyblish/vendor/__init__.py#L5

Because of this, if you have a tool using `click`, it picks up your vendor library which is a bit old.. You seems to be using "vendorised" libraries from the `vendor` module, so why adding them to `sys.path`?

https://github.com/pyblish/pyblish-base/blob/8588808a0e7e6f819e618909359502c5c8327e2e/pyblish/cli.py#L30

https://github.com/pyblish/pyblish-base/blob/841f40821507964389adac01683ac86f745bb5fe/run_testsuite.py#L10

**Comment by mottosso** [comment]
That's a good question, thanks for pointing this out.

It was quite a long time ago, but I remember Click (or possibly another library) didn't support being vendorised. It used absolute references internally, which I "solved" by making it happy and putting it on the absolute path.

It doesn't look necessary anymore, but are you able to quickly test this? E.g. remove that line, and see if anything you normally do still works.

**Comment by buddly27** [comment]
For what I can see, all vendorised libraries are being imported via the `vendor` module.

* **iscompatible**: Used in [plugin.py](https://github.com/pyblish/pyblish-base/blob/acf97ef9fdc2fc506daac7817db99073a79a7c56/pyblish/plugin.py#L38)
* **six**: Used in [plugin.py](https://github.com/pyblish/pyblish-base/blob/acf97ef9fdc2fc506daac7817db99073a79a7c56/pyblish/plugin.py#L38), [lib.py](https://github.com/pyblish/pyblish-base/blob/acf97ef9fdc2fc506daac7817db99073a79a7c56/pyblish/lib.py#L10), [tests/lib.py](https://github.com/pyblish/pyblish-base/blob/acf97ef9fdc2fc506daac7817db99073a79a7c56/tests/lib.py#L10), [tests/pre11/test_cli.py](https://github.com/pyblish/pyblish-base/blob/acf97ef9fdc2fc506daac7817db99073a79a7c56/tests/pre11/test_cli.py#L7) and [tests/pre13/test_plugin.py](https://github.com/pyblish/pyblish-base/blob/acf97ef9fdc2fc506daac7817db99073a79a7c56/tests/pre13/test_plugin.py#L12)
* **click**: Used in [cli.py](https://github.com/pyblish/pyblish-base/blob/acf97ef9fdc2fc506daac7817db99073a79a7c56/pyblish/cli.py#L30), [tests/test_cli.py](https://github.com/pyblish/pyblish-base/blob/acf97ef9fdc2fc506daac7817db99073a79a7c56/tests/test_cli.py#L13) and [tests/pre11/test_cli.py](https://github.com/pyblish/pyblish-base/blob/acf97ef9fdc2fc506daac7817db99073a79a7c56/tests/pre11/test_cli.py#L11)
* **mock**: Used in [run_testsuite.py](https://github.com/pyblish/pyblish-base/blob/acf97ef9fdc2fc506daac7817db99073a79a7c56/run_testsuite.py#L10), [tests/test_plugin.py](https://github.com/pyblish/pyblish-base/blob/acf97ef9fdc2fc506daac7817db99073a79a7c56/tests/test_plugin.py#L4), [tests/pre11/test_cli.py](https://github.com/pyblish/pyblish-base/blob/acf97ef9fdc2fc506daac7817db99073a79a7c56/tests/pre11/test_cli.py#L15), [tests/pre11/test_logic.py](https://github.com/pyblish/pyblish-base/blob/acf97ef9fdc2fc506daac7817db99073a79a7c56/tests/pre11/test_logic.py#L8), [tests/pre11/plugins/conform_instances.py](https://github.com/pyblish/pyblish-base/blob/acf97ef9fdc2fc506daac7817db99073a79a7c56/tests/pre11/plugins/conform_instances.py#L4) and [tests/pre11/plugins/failing/conform_instances_fail.py](https://github.com/pyblish/pyblish-base/blob/acf97ef9fdc2fc506daac7817db99073a79a7c56/tests/pre11/plugins/failing/conform_instances_fail.py#L5)

Unit tests are running without the `sys.path.insert` and the command line seems to work fine as well.

**Comment by mottosso** [comment]
Thanks for the thorough investigation @buddly27. Would you mind making a PR for this, such that the automated tests can kick in? I expect that if those still pass, we'll be good to go.

**Comment by buddly27** [comment]
Done :)
