### ISSUE TITLE
Review Extractor

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-base#37]
- Produces empty pngs

**Comment by mottosso** [comment]
@madoodia had this issue too. What OS and version are you on? It works for me on Windows 8.1

To be clear, the pngs are all black/transparent?

**Comment by tokejepsen** [comment]
OS: windows 7
Maya: 2014

All pngs are black/transparent.

**Comment by mottosso** [comment]
Are you able to produce a playblast manually, with the off-screen option? Are you running Aero in Windows?

**Comment by tokejepsen** [comment]
Yeah, can playblast offscreen manually. Not running Aero.

I can have a look at it later, and see if I can find the bug.

**Comment by mottosso** [comment]
That's odd. Ok, thanks, let me know what you find out.

**Comment by madoodia** [comment]
OS: Windows 8.1
Maya: 2014
PNG give me Dark images
when i test it with tiff (manually in maya) it give me good blast.
:)

On Mon, Aug 18, 2014 at 1:09 PM, Marcus Ottosson notifications@github.com
wrote:

> That's odd. Ok, thanks, let me know what you find out.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/abstractfactory/publish/issues/37#issuecomment-52465412
> .

## 

Bests,
madoodia

**Comment by mottosso** [comment]
So the only one it's really working for is myself. Classic! :)

**Comment by tokejepsen** [comment]
the bug: https://github.com/abstractfactory/publish/blob/master/publish/plugins/extract_review.py#L120, removing this line made it work for me

**Comment by mottosso** [comment]
I'm getting the same thing over here now. So what `refresh` does is to prevent Maya from updating until the process is finished. I had some graphical pops when switching back the camera in the `finally:` clause which got resolved by the `refresh` but I guess it also stops the viewport from actually producing any color. Good find.

**Comment by mottosso** [comment]
This has been fixed!
