### ISSUE TITLE
Abstract properties of Filter

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-base#44]
It just occured to me that the mandatory properties of Filter et. al. should really be abstract properties. E.g.

``` python
class Filter(object):
    @abc.abstractproperty
    def families(self):
        pass
```

So that whomever implements a plugin, will also have to implement the properties. E.g.

``` python
class MyFilter(Filter):
    @property
    def families(self):
        return ['maya']
```

At the moment, you could implement a plugin, but forget about these properties which would make your plugin not work.

> edited: Typo

**Comment by tokejepsen** [comment]
So that would be for families and hosts?

**Comment by mottosso** [comment]
So far, yes. And any other mandatory properties we'll end up with.

**Comment by mottosso** [comment]
Reopening this due to `@properties` not being accessible in classes that hasn't been instantiated yet, resulting in messier code.

``` python
# E.g.
for PluginClass in publish.plugin.discover():
    plugin = PluginClass(instance)
    assert plugin.hosts == ['maya']

# As opposed to:
for plugin in publish.plugin.discover():
    assert plugin.hosts == ['maya']
```

And in cases where the plugin takes different arguments, such as the Selector taking a Context and the Validator taking an Instance, further checks has to be made prior to getting hosts and families. It'd be more efficient if we could check compatibility _before_ doing any instantiation, as was the case prior to this adjustment.

Thoughts?

**Comment by mottosso** [comment]
This has been restored to non-properties due to the above explanation.
