### ISSUE TITLE
About versioning

### ISSUE THREAD

**Issue by achayan** [pyblish/pyblish-base#47]
Hey Guys,

A quick question about version numbers, why we need 0 in version numbers like v001. Instead of that we can just start with v1.ma which will give us more flexibility when we sort stuff right ?.

**Comment by tokejepsen** [comment]
Its quite common practise to pad the version number, so they are sorted visually in any OS.

> Instead of that we can just start with v1.ma which will give us more flexibility when we sort stuff right ?.

What do you mean by more flexibility?

**Comment by achayan** [comment]
Right its a common practise but most of the big studios just start version with v1. flexibility means if we want to strip version numbers or sort it those kind of situations its handy. This is just a suggestion.

**Comment by tokejepsen** [comment]
What is the versioning in relation to? Is it for the test files?

I don't mind going with any number of padding or none.

**Comment by mottosso** [comment]
> A quick question about version numbers, why we need 0 in version numbers like v001. Instead of that we can just start with v1.ma which will give us more flexibility when we sort stuff right ?

The original source of that is probably convention and, as Toke mentioned, is probably based on how the OS filters versions in its file-browser.

I wouldn't necessarily say it makes for more flexibility one way or another though. Having leading zeroes does simplify finding versions in a file-browser, while on the other hand adds an additional step to parsing them in code. Larger studios probably make less use of file-browsers so it makes sense to not bother with that aspect.

The test files are the only files I can think of that currently uses this convention, but the files Publish produces won't have much to do with it, as far as I can tell.

Does that answer your question?

**Comment by mottosso** [comment]
Assuming this is all good, feel free to re-open @achayan if you have any more comments!
