### ISSUE TITLE
QML

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-base#48]
I'd like to propose evaluating QML for the GUI portion of this project. 

For those new to QML, I would recommend wetting your beaks in these videos.
- [Live Coding](https://www.youtube.com/watch?v=P4kv-AoAJ-Q) 
- [Qt Quick Controls](https://www.youtube.com/watch?v=_6_F6Kpjd-Q)

In a nutshell, QML is the successor of Widgets - officially - and the future of UI development  - in my opinion :)

Some of the immediate benefits are.
- **Performance** - identical to native Qt code (because it is)
- **Look** - styling and animations are a primary concern of the language itself, think CSS
- **Future** - QWidget is officially complete and won't be getting any new features. 
  (Remind me to post a reference to that statement)

Whereas some disadvantages are.
- It's **new to us**, which means we'd all be re-learning things
- It's **new technology**, which means bugs with scarce resources for help

Some learning resources.
- [Qt DevDays](https://www.youtube.com/channel/UCsyT1C1M-QoHQREjsixgayQ) - These are some recordings of conferences held about Qt in general, including QML and should provide some perspective on what is it and where it is going.
- [QML Book](http://qmlbook.org/) - A nice getting-started guide
- [Limetext](https://github.com/limetext/lime) - A Sublime Text port to Go and QML, for some QML used in an actual application.

Discuss!

**Comment by ljkart** [comment]
What about compatability with Maya and other application, I dont think Maya  support QDeclarative(QtQuick)

**Comment by mottosso** [comment]
Yes, good question.

The way I've been approaching the GUI and Publish in general so far is for it to run as a separate process, outside of Maya and all other hosts, and for it to communicate over an inter-process layer, such as TCP, using ZeroMQ.

From the users point of view, this isn't noticeable - which is important - but for us it means we can develop a single application and have it run identically across hosts, as well as standalone.

This is something I'd propose regardless of whether or not we got with with QML, because even though we are fortunate enough to have some of our hosts ship with Qt, none of them use the same version and some of them doesn't have access to it at all. And so relying on this luxury would mean quite a bit of additional glue to compensate for their differences and quite a bit of additional bugs, compared to the one-off cost of getting started with inter-process communication.

It's something I've been doing internally for other apps and something I'm familiar with and know works well, but this is something we should discuss here as well.

> Edited: Better wording

**Comment by madoodia** [comment]
Very Good Issue!
I really like QML, it is so nice. and i promice if you use that you will love it.
thanks for your choice marcus.
i agree with using QML.

**Comment by achayan** [comment]
QML will be better a good post about qml : http://jontheechidna.wordpress.com/2012/05/19/my-thoughts-on-qml-and-the-desktop/

**Comment by mottosso** [comment]
@achayan, nice link! 

From the article:

> As of now, Qt does not offer a set of common components like we see with the current set of QWidgets. 

This article was from 2012 and this has been implemented in Qt 5, as shown in the Qt Quick Controls video above.

**Comment by ljkart** [comment]
Yeah, this is a nice thought. 
But if we are thinking somthing outside then even we can  consider web apps with
huge support of HTML5 and CSS3 with other libraries!

**Comment by mottosso** [comment]
Hi all,

Here's an update on the GUI/QML front. I've been spending the past week reading up on QML and am now finally able to say I'm comfortable designing moderately complex layouts.

So I present to you, a first cut, complete with animations and inter-process communication.

![](https://cloud.githubusercontent.com/assets/2152766/4982100/ccc3dcf2-690f-11e4-91b5-f4fd71e4bc50.gif)
- https://github.com/pyblish/pyblish-qml

### Architecture

We previously spoke about utilising ZeroMQ for IPC, but a slightly less involved method came to mind which is being used in this example; a Flask server with a RESTful interface. The benefit of this is native support in Python (and other languages) as opposed to the custom-compiled version of ZMQ we'd have to make otherwise.

There is however one major downside; talking back to our tool from hosts isn't as straightforward using this approach, but I think I've got an idea about where to go with that which I'll try and implement tomorrow. It's important as we need to display real-time information about what's going on in a host.

Bottom line is, installing Pyblish along with it's GUI is now a matter if pip install, no compilation or other tricks required!

### From here

Next step is running a provider from within Maya, each host in fact, that the GUI will hook into upon start up. From there, the GUI will take over the publishing mechanism, executing each step so as to provide real-time feedback to the user, including the ability to cancel and pause.

I tried my best to match our mockups from [the pull-request](https://github.com/abstractfactory/pyblish/pull/72) of @madoodia, and think there's lots of places to go at this point; for one, we'll need a visual method of selecting and inspecting instances - such as which plug-ins are about to process each - along with room for their status updates to take place.

Let me know what you think, and if you want to run it, simply install Qt 5.3 and run it! However, for integration, you'll have to be a little patient as I take her through the steps.

Best,
Marcus

**Comment by tokejepsen** [comment]
Amazing work @mottosso:) Look forward to taking it for a spin in Nuke and Modo!

**Comment by mottosso** [comment]
Thanks, Toke.

About Modo, there is something you could try out, in preparation for the GUI. I'm fairly confident Nuke won't have a problem with it, but not sure about Modo.

We'll need to start a thread, from Python, and keep it alive for the duration of the Modo process. It'll start when running Modo, and get killed together with Modo upon quitting. In Maya, this isn't a problem, as Python is running continuously; but Modo may launch an interpreter upon running each command and thus kill any threads it starts immediately.

Here's a simple test, if you could run this, and ensure it does count all the way to 10, then we're in the clear.

``` python
import time
import threading

def counter():
    count = 10
    while True:
        if count <= 0:
            print "Done"
            return
        print "Number %i" % count
        count -= 1
        time.sleep(1)


t = threading.Thread(target=counter)
t.start()
```

**Comment by mottosso** [comment]
Here's an initial version for Maya.

![untitled](https://cloud.githubusercontent.com/assets/2152766/4993236/ce4e5018-69a3-11e4-897e-33cba8e2228d.gif)

**Featurelist**
- Visualise current instance in the scene
- Visualise each instance's family
- Publish from GUI

I'll return with more details on how to set this up.

Best,
Marcus

**Comment by tokejepsen** [comment]
Nice work on the Maya side, looks good so far.

> Here's a simple test, if you could run this, and ensure it does count all the way to 10, then we're in the clear.

This is crashing Modo:) I'll ask on the forums about it.

**Comment by mottosso** [comment]
> This is crashing Modo:)

Hah, did not expect that. :)

**Comment by tokejepsen** [comment]
Waiting on forum respondes but it doesn't look good for python threading according to this; http://community.thefoundry.co.uk/discussion/topic.aspx?f=37&t=75764. Its a year old thread, but I don't think it has been addressed yet.

**Comment by tokejepsen** [comment]
And python threading has been confirmed not to work in Modo.

**Comment by mottosso** [comment]
Ok, we may still be able to work around that. 

We'll need one of these:
1. A method (any method) of executing commands from outside of Modo; like Maya's commandPort. 
2. Any way of setting up a server; possibly via a plug-in. How does one write plug-ins for Modo?
3. Can Lua run in a separate thread?

Can you do some digging?

Overall, smells like a good opportunity to get Pyblish into their heads; running custom GUI's in Modo. That's gotta be gold for those who don't even have PyQt to play around with. :)

**Comment by mottosso** [comment]
This looks promising from a Lua perspective.
- http://www.lua.org/pil/9.4.html

The question is, can Lua do this from within Modo?

**Comment by tokejepsen** [comment]
Commandports should be feasible; http://sdk.luxology.com/wiki/Telnet

Could probably open a port from the Pyblish startup scripts, and run through that. Personally I haven't used commandports before, so don't know anything about it.

**Comment by mottosso** [comment]
That.. is archaic. But it will do. :) Let me have a think about how to go about it.

Off the top of my head; I'd imagine that when booting up Modo, we'll also boot up an additional, windowless process. This will act as our server and it will communicate with Modo's telnet client, possibly using this: http://sdk.luxology.com/wiki/Modo_Socket_comms_wrapper

The process could either be started from a wrapper script, or from within Modo through Python's `subprocess.Popen`.

Either way, this will work just fine!

**Comment by mottosso** [comment]
Here's the schedule for the coming days, let me know if there's anything you value more or less, or if anything is missing. These are meant to be the highest priorities in a first release of a GUI for Pyblish.

**System**
- [x] Visualise version of Pyblish available to host (e.g. 1.0.10)
- [x] Visualise which Host we are communicating with (e.g. Maya)
- [x] Support multiple hosts/instances of host

**General**
- [x] Visualise which plug-ins exists (similar to current log messages)
- [x] Toggle plug-in on/off (if optional)
- [x] Visualise which plug-in paths have been considered
- [x] Toggle paths on/off (for debugging)
- [x] Visualise which plug-ins apply to which instance

**Run-time**
- [x] Upon running, which plug-in is currently running, along with it's messages
- [x] If things go wrong, which instance is responsible
- [x] Along with helpful information about what to do about it.

More things will undoubtedly come to mind as we go along, let's make sure to get the most necessary out first and then work our ways towards perfection.

**Comment by tokejepsen** [comment]
sounds pretty good to me:)

**Comment by mottosso** [comment]
**Additional, non-critical features**
- [x] Run individual plug-in on selected instance
- [ ] Inspect parent asset of instance
- [ ] Commenting

### Individual plug-in

This can be useful in cases where a user knows he might be violating certain standards and just wants to run it through the test, or if a test failed before and some changes has been made, the user can then run the test in isolation until it works allright.

### Inspecting Parent Asset

This is a major feature and will align itself with the Web Frontend when the time is right. In a nutshell, I'd like for users to be able to inspect properties of the asset from which an instance was made.

Inspect, such as visualise any and all information there is about it - such as a thumbnail, original author, preview data such as meshes or additional screenshots, versions (although managing versions is NOT the responsibility of this GUI) and finally, a means of communicating/commenting on a per-asset/instance basis.

### Commenting

Of course, we'd like for users to be able to provide additional, human information along with a publish, if any is available to give. This should be possible from an overall perspective - one comment for an entire publish, regardless of how many instances are going out (this may be the most common type of comment) - but also on a per instance basis, in cases where certain instances    require special attention.

**Comment by ljkart** [comment]
Hi Marcus,
 That was excellent stuff, looking forward to see much more.

Thanks
Liju K

**Comment by mottosso** [comment]
Take a few moments to have a look at some of the proposed user interface additions, here.
- https://github.com/pyblish/pyblish-qml/issues

Each issue comes with illustrations and animations.

Let me know what you think, and subscribe to the repo if you want to stay on top of what's happening or want to join in!

**Comment by mottosso** [comment]
This one is ongoing.
- https://github.com/pyblish/pyblish-qml

**Comment by mottosso** [comment]
After a couple of months implementing a graphical user interface in QML, here are a few more points I've discovered along the way.
- Shared experience and knowledge base for all developers; not just PyQt which is tiny compared to its C++ equivalent.
- Consistent UI/UX resources for all things QML. With Python and C++, a majority is about non UI/UX matters, such as optimisations and techniques.
- Shared knowledge base with Web Developers; Javascript, Canvas and WebGL APIs.

### Performance

Performance comes in two flavours; playback and initialisation. Playback performance is good, which facilitates smooth animation and even games. It's pure OpenGL which means it reaps the benefits of the graphics card. Initialisation on the other hand means generating geometry and textures and passing that to the GPU, something I'd expect to take longer but after some tests I might have to change my mind.
- See [tests](https://gist.github.com/mottosso/3ed95104e8dd484b57b8).

QML handles simple tasks about 26x faster in the best case, 42x slower in the worst case, with an average of about 12x faster.
