### ISSUE TITLE
Refactor Filter and Selector to both take Context as input

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-base#49]
@tokejepsen mentioned [here](https://github.com/abstractfactory/publish/issues/40#issuecomment-52787305) in #40:

> Maybe we can even initialize both Validators and Selectors with a context, and get that same base class?

Which rang a bell in my head and I'll have a look at implementing this tomorrow morning.

Currently, Selectors are instantiated with a Context and adds Instances to it, whereas the other filters - validation, extraction and conform - are each instantiated with an Instance and operates on its members (the nodes in the scene).

In a way, we have been pre-determining which instances goes with which plugin. Instead, we could potentially pass the entire context to each validator and trust it to only pick instances relevant to itself. E.g. passing a context of 3 instances - e.g. 2 of family "model" and 1 of family "animation" - to a validator of family "model" would choose to only validate the 2 models, and leave the animation family alone.

**Comment by tokejepsen** [comment]
>  Instead, we could potentially pass the entire context to each validator and trust it to only pick instances relevant to itself. 

We could also provide a function that filters the instances from a parent class. So in the validators we can call `self.instances`, and that will return the relevant instances.

**Comment by mottosso** [comment]
> We could also provide a function that filters the instances from a parent class. So in the validators we can call self.instances, and that will return the relevant instances.

I'm giving this a go, but it looks like we'll have to refactor `abstract.py` for this to work.

For `Filter.instances` to work, `Filter` would need access to `domain.current_host()` which is not only in a separate module, a module that imports `abstract.py`, but is also something that reaches out onto the OS, breaking the encapsulation of the baseclasses.

The simplest thing I can think of would be to slap all modules together into a big `everything.py` where everything can have access to everything. But I'd really rather not.

Do you have any ideas?

**Comment by tokejepsen** [comment]
I wasn't thinking the `self.instances` call through, so more of a wishful thinking I guess:)
I think it would be alright for now, to have the filtering of instances in each plugin. Anybody wanting to write a plugin will be looking through existing ones anyway to understand the process. Refactoring for the future if we find this to work out well.

**Comment by mottosso** [comment]
No it was certainly a good idea, and I found it very necessary once I got into it.

The alternative is for the author of each plugin to handle filtering per family on his own, within each plugin, which produces a lot of duplicate code and would be easily prone to error. The only thing necessary should be the implementation of `process()` to handle a single Instance, as all other instances would be identical, similar to how it works at the moment.

**Comment by mottosso** [comment]
I'm having difficulties wrapping my head around this. @tokejepsen, would you mind having a go? I can't figure out how to give the Context to both Selectors and the other plugins.

**Comment by tokejepsen** [comment]
Sure, i'll give it a go soon.

**Comment by mottosso** [comment]
This has been fixed by @tokejepsen!
