### ISSUE TITLE
Integrations

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-base#55]
Hi all,

I'd like to propose a few integrations, along with formalising the one we've been working on for Maya, in accordance with the current [Pull-Request](https://github.com/abstractfactory/publish/pull/54) about preparing for GUI development.

I've written up a WIki page for each integration, stating the problem domain and a potential architecture, but here's a summary.
# [![asana-publish](https://cloud.githubusercontent.com/assets/2152766/4027380/bee8c076-2c2d-11e4-9f17-5b11eb864b00.png)](https://github.com/abstractfactory/publish/wiki/publish-for-asana)

**Publish for Asana** - Essentially in the form of a few plugins, conform plugins. Each plugin could be responsible for a particular update, such as commenting on tasks associated with the particular asset being published, or updating the project status as a whole. Users subscribed to tasks would then be able to retrieve updates via mail or directly in Asana.
- [More information](https://github.com/abstractfactory/publish/wiki/publish-for-asana)
# [![git-publish](https://cloud.githubusercontent.com/assets/2152766/4027384/cbb0e5f4-2c2d-11e4-8563-27e28bb3214b.png)](https://github.com/abstractfactory/publish/wiki/publish-for-git)

**Publish for Git** - Sort of a "eating your own dogfood" whilst developing. :) This integration is about running validations upon each commit, push, pull or merge, either directly after or before.
- [More information](https://github.com/abstractfactory/publish/wiki/publish-for-git)
# [![maya-publish](https://cloud.githubusercontent.com/assets/2152766/4027386/e0b89a82-2c2d-11e4-86c9-6befafe4ac26.png)](https://github.com/abstractfactory/publish/wiki/publish-for-maya)

**Publish for Maya** - Finally, what we've been doing so far, but in alignment with other integrations. 
- [More information](https://github.com/abstractfactory/publish/wiki/publish-for-maya)

The way I'm imagining this to work is for each of these to have their own corresponding GitHub repositories and for each to be installable via pip.

``` bash
$ pip install publish
$ pip install publish-asana
$ pip install publish-git
```
# Further

We spoke briefly about how we can safely assume any particular conventions employed within any production; like assuming everyone uses references or namespaces for rigs in Maya or whether they use Shotgun for asset tracking.

I think that with integrations separated this way, we could potentially provide a full suite of configuration options, with GUI's, per integration.

For example, to use the Asana integration, we could assume that users tag their selections (be it object sets or transforms etc.) with the appropriate task reference within Asana and that this tag is called "asanaRef".

We could also provide an individual configuration setup for Asana, with this as an option, possibly with its own GUI to go with it.

``` python
# config.json
{
    "asanaReference": "my_custom_name"
}
```

On that note, we could start providing much more specific integrations, that make assumptions about how people rig or model or texture and simply provide configuration for when things differ.

``` python
class ValidateCharacterControls(Validator):
     def process(self, context):
         """Stress test controllers

         The test will ensure that no ik-flipping occurs and that the
         mesh isn't experiencing stretch beyond 140%

         """
```

This particular example assumes that controls are readily available, and that there is some means of conforming the amount of stretch taking place upon a mesh, such as via [SOuP](http://www.soup-dev.com/) or Fabric.
# Even further

With this in mind, it would allow third-party developers the ability to provide suites of "best practices" or "production techniques" as an individual bundle, installable via pip, that captures how a particular studio or product does things.

``` bash
$ pip install publish-ilm-rigging
$ pip install publish-glassworks-conform
$ pip install publish-shotgun-review
```

Ultimately facilitating conventions on a global scale that can be reused and perfected by anyone.

**Comment by tokejepsen** [comment]
Sounds pretty good to me:)

**Comment by mottosso** [comment]
Okay, this is in progress, the first actual, isolated integration is Maya and is hosted here:

https://github.com/abstractfactory/pyblish-maya

It'll get it's own Wiki and installation instructions, along with its own issue-tracking.
