### ISSUE TITLE
Publish as a Namespace Package

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-base#56]
I just came across an interesting feature of Python that I'd never heard about before and figure I'd initiate a discussion about the prospect of using it for Publish.
# The Problem

The problem is related to dividing our project into individual repositories and thus ending up with lots of top-level packages on the users file-system. For example, if we split up the project without making it a namespace package, it may look something like this:
- [ ] ![dir](https://cloud.githubusercontent.com/assets/2152766/4041935/76446912-2cfd-11e4-8f04-df5e00e861ff.png) publish
- [ ] ![dir](https://cloud.githubusercontent.com/assets/2152766/4041935/76446912-2cfd-11e4-8f04-df5e00e861ff.png) publishmaya
- [ ] ![dir](https://cloud.githubusercontent.com/assets/2152766/4041935/76446912-2cfd-11e4-8f04-df5e00e861ff.png) publishhoudini
- [ ] ![dir](https://cloud.githubusercontent.com/assets/2152766/4041935/76446912-2cfd-11e4-8f04-df5e00e861ff.png) publishasana

``` python
import publish.backend
import publishmaya
import publishasana
```

To install, we could do

``` bash
$ pip install publish
$ pip install publish-maya
```
# The Solution
- [ ] ![dir](https://cloud.githubusercontent.com/assets/2152766/4041935/76446912-2cfd-11e4-8f04-df5e00e861ff.png) publish.main
- [ ] ![dir](https://cloud.githubusercontent.com/assets/2152766/4041935/76446912-2cfd-11e4-8f04-df5e00e861ff.png) publish.maya
- [ ] ![dir](https://cloud.githubusercontent.com/assets/2152766/4041935/76446912-2cfd-11e4-8f04-df5e00e861ff.png) publish.houdini
- [ ] ![dir](https://cloud.githubusercontent.com/assets/2152766/4041935/76446912-2cfd-11e4-8f04-df5e00e861ff.png) publish.asana

If we instead split Publish up as a namespace package, we could get the same benefits as with separated repositories and instead end up with:

``` python
import publish.main
import publish.maya
import publish.asana
```

That is, maintaining everything within a single namespace - `publish`

Development, distribution and installation works similarly.

``` bash
$ pip install publish.main
$ pip install publish.maya
$ pip install publish.asana
```

With the added benefit of opening up for using "publish.main" or similar as opposed to "pypublish" as "publish" is already occupied.
# How it works

A namespace package is..

> ..a mechanism for splitting a single Python package across multiple directories on disk. - PEP420

**References**
- [stackoverflow.com](http://stackoverflow.com/questions/1675734/how-do-i-create-a-namespace-package-in-python)
- [PEP420](http://legacy.python.org/dev/peps/pep-0420/)
- [pythonhosted.org](https://pythonhosted.org/setuptools/setuptools.html#namespace-packages)
- [labs.oreilly](http://chimera.labs.oreilly.com/books/1230000000393/ch10.html#_discussion_172)
- [wyattbaldwin.com](http://wyattbaldwin.com/2014/02/07/pep-420-namespace-packages-somewhat-surprising/)

Which in practice means that we can do:

``` bash
$ pip install publish.main
```

At this point, we've got what we would expect:

``` python
>>> import publish.main
```

Which, when installed, looks like this:
- [ ] ![dir](https://cloud.githubusercontent.com/assets/2152766/4041935/76446912-2cfd-11e4-8f04-df5e00e861ff.png) `site-packages`
  - [ ] ![dir](https://cloud.githubusercontent.com/assets/2152766/4041935/76446912-2cfd-11e4-8f04-df5e00e861ff.png) `publish`
    - [ ] ![dir](https://cloud.githubusercontent.com/assets/2152766/4041935/76446912-2cfd-11e4-8f04-df5e00e861ff.png) `main`
      - [ ] ![file](https://cloud.githubusercontent.com/assets/2152766/4041938/82aabf1c-2cfd-11e4-8625-490f55adccab.png)`__init__.py`

> Note that there is no ![file](https://cloud.githubusercontent.com/assets/2152766/4041938/82aabf1c-2cfd-11e4-8625-490f55adccab.png) `__init__.py` in ![dir](https://cloud.githubusercontent.com/assets/2152766/4041935/76446912-2cfd-11e4-8f04-df5e00e861ff.png) `publish`.

However, we can't do:

``` python
>>> import publish.maya
ImportError("No module named maya")
```

Until we do:

``` bash
$ pip install publish.maya
```

Which installs an additional sub-package of `publish`, as such:

``` python
>>> import publish.maya
```

So now the install looks like this:
- [ ] ![dir](https://cloud.githubusercontent.com/assets/2152766/4041935/76446912-2cfd-11e4-8f04-df5e00e861ff.png) `site-packages`
  - [ ] ![dir](https://cloud.githubusercontent.com/assets/2152766/4041935/76446912-2cfd-11e4-8f04-df5e00e861ff.png) `publish`
    - [ ] ![dir](https://cloud.githubusercontent.com/assets/2152766/4041935/76446912-2cfd-11e4-8f04-df5e00e861ff.png) `main`
      - [ ] ![file](https://cloud.githubusercontent.com/assets/2152766/4041938/82aabf1c-2cfd-11e4-8625-490f55adccab.png)`__init__.py`
    - [ ] ![dir](https://cloud.githubusercontent.com/assets/2152766/4041935/76446912-2cfd-11e4-8f04-df5e00e861ff.png) `maya`
      - [ ] ![file](https://cloud.githubusercontent.com/assets/2152766/4041938/82aabf1c-2cfd-11e4-8625-490f55adccab.png)`__init__.py`
# Conclusion

I've never worked with this before and so it's possibly buggy or illogical in other fronts. The only benefit I can think of is cosmetic, can you think of anything else?

I got inspired by this repository, which is distributed as a namespace package:
- https://github.com/pyQode

So, question is, cool or not cool?

**Comment by ghost** [comment]
I quite like the idea of nested packages rather than having all of them in
the top-level. Maybe it is just me but it looks more clean and it still
makes sense. Having said that, I don't know if that could end up causing
problems of any kind.

## 

David Martinez - Technical Animator

Email: david.martinez.anim@gmail.com
Website: http://www.elusiveideas.com

**Comment by mottosso** [comment]
Hey David, thanks for sharing. I'm with you in that it looks better. Maybe the only way to know whether it'll cause trouble is to give it a try..

I mocked up a repo to try things out here:
- https://github.com/mottosso/jolt.core
- https://github.com/mottosso/jolt.gui

To install, do:

``` bash
$ pip install https://github.com/mottosso/jolt.core.git
$ python
Python 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import jolt.core
>>> jolt.core.myfunc()
jolt.core function
```

This will produce a `jolt` namespace package, with a subpackage of `core`. `jolt.gui` then imports `jolt.core` and imports and runs the same function:

``` bash
$ pip install https://github.com/mottosso/jolt.gui.git
$ python
Python 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import jolt.gui
>>> jolt.gui.guifunc()
jolt.core function
```

One immediate disadvantage is the additional namespace for all our code.

``` python
# Instead of
import publish.backend.plugin

# We'll have to go
import publish.main.backend.plugin
```

However:

> Namespaces are one honking great idea -- let's do more of those! - [PEP20](http://legacy.python.org/dev/peps/pep-0020/)

**Comment by ghost** [comment]
I will give it a go and see how it goes.

As for the additional namespace I don't think this is a big deal as imports
are done once and we can always give it an alias using the following syntax:

```
import publish.main.backend.plugin as desiredAlias
```

Or would you rather keep the whole namespace?

## 

David Martinez - Technical Animator

Email: david.martinez.anim@gmail.com
Website: http://www.elusiveideas.com

**Comment by mottosso** [comment]
I generally stick to full namespaces and would advocate for this for the Publish development, as it makes it very clear where things are coming from. 

I use aliases only locally and only when it would otherwise cause lines to pass the 80-characters mark, e.g.

``` python
def process(self, context):
    """Allow nodes of appropriate names through"""

    instances_by_plugin = publish.main.backend.plugin.instances_by_plugin
    for instance in instances_by_plugin(instances=context, plugin=self):
                ...
```

**Comment by ghost** [comment]
Ah! Fair enough
:-)

**Comment by mottosso** [comment]
An interesting thing to note from installing the `jolt` distribution, is how the package is located within site-packages which is on the PYTHONPATH, and is treated as a package, but doesn't have a `__init__.py` in it, which is normally what makes a folder into a package.

Python is performing some magic here, you can see it if you import jolt and print it.

``` python
>>> import jolt
>>> print jolt
<module 'jolt' (built-in)>
>>> help(jolt)
Help on package jolt:

NAME
    jolt

FILE
    (built-in)

PACKAGE CONTENTS
    core (package)
    gui (package)
```

**Comment by tokejepsen** [comment]
+1 for unified package

**Comment by mottosso** [comment]
I contacted the developer of pyQode (above) about Namespace Packages, here's what he had to say:

> Hi Marcus,
> 
> I initially learned about namespace packages through the zope project (http://www.zope.org/ ). I have been using them for a year now and have been pretty happy with this solution. It gives a clean separation of functionality and their dependencies. IMHO it feels more pythonic but some people might find it disturbing at first.
> 
> The only pitfall I am aware of is that you must always install all your packages the same way or the import machinery will fail. E.g. you cannot install a package with setup.py install and another one with setup.py develop. This might also be true with packages installed with a package manager on linux (.deb/.rpm). The difference is that the develop command installs .egg.link files while the install command creates a directory with the name of your namespace package (publish) and every new package that you install will be installed into this directory (publish/maya, publish/core...). (Note that this is only true for python 3.4. Other python versions do that differently, by creating a special file which points to the individual packages... The internals of namespace packages are quite tricky^^).
> 
> I haven't had any other issues with namespace packages and would definitely use them for new projects such as yours.
> 
> Regards,
> 
> Colin

**Comment by tokejepsen** [comment]
Still sounds good to me:)

**Comment by mottosso** [comment]
Cool. :)

I'm having a go at this at the moment to see how this will work in practice, and the one thing I noticed right away was that running a module - plugin.py - when in a namespace package takes considerably longer to finish.

500-600 ms, compared to 200-300 when in a standard package.

It might be circumstantial, and I'll have to run further tests, but there was mention of this in the PEP420.

> If a developer knows that her package will never be a portion of a namespace package, then there is a performance advantage to it being a regular package (with an **init**.py). Creation and loading of a regular package can take place immediately when it is located along the path. With namespace packages, all entries in the path must be scanned before the package is created.

Which in practice may mean, the more packages are on an individuals PYTHONPATH, the slower our package would run.

Whether this matters very much I'll leave until we can draw actual conclusions from usage in the field, it seems as though it will at least not have any performance penalty once the PYTHONPATH has been fully parsed. So, no run-time disadvantage.

**Comment by mottosso** [comment]
There seems to be an issue with namespace packages and Maya.

``` bash
ImportError: No module named pkg_resources
```

pkg_resources comes with the packages SetupTools which is a standard library package since Python 2.6, but it doesn't seem to ship with Maya 2015, and it's quite possible that it doesn't ship with other hosts either.

Since we must be able to run our backend from Maya, along with its individual distribution, we'll have to use namespace packages and namespace packages requires this module.

I see three alternatives.
1. End-user installs setuptools into Maya, before using Pyblish.
   http://eoyilmaz.blogspot.co.uk/2014/02/how-to-install-setuptools-for-maya-and.html
2. We hack, by including `pkg_resources.py` in each package.
3. We hack, by not using it in Maya, but use it everywhere possible.

**Comment by ColinDuquesnoy** [comment]
Antoher option is to use [zipimport](https://docs.python.org/2/library/zipimport.html). Basically you put all your required dependencies in a zip archive, you append the path of the zip archive to the python path and load packages from the archive.

This is what I am doing when running the pyqode backend on a foreign interpreter (users do not have to install pyqode and all its dependencies when targetting python 2 or a virtualenv).

**Comment by mottosso** [comment]
Thanks Colin, does that mean I'll have to include the dependency, pkg_resource.py, with each namespace package? Are you including only pkg_resource.py, or all of setuptools? Do you have a link to where this is happening in pyqode?

**Comment by ColinDuquesnoy** [comment]
Actually I am not including setuptools but other packages specific to pyqode.python (jedi, pep8, pyflakes and the pyqode backend scripts). The zip path is passed to the backend process and simply appended to sys.path (https://github.com/pyQode/pyqode.python/blob/master/examples/qidle/libraries.zip, https://github.com/pyQode/pyqode.python/blob/master/examples/qidle/qidle/main_window.py#L106, https://github.com/pyQode/pyqode.python/blob/master/pyqode/python/backend/server.py#L40)

**Comment by mottosso** [comment]
I'm comfortable including vendor packages, that's not my problem. The problem is including a package that significantly alters the overall behaviour of Python's package discovery mechanism, and whether it is safe to do so in all environments, such as Maya, but also Travis and ReadTheDoc amongst others.

For example, if `pkg_resources` can't be found, then Python seems to only discover the first-found package.

``` python
import publish.backend
import publish.maya
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named publish.maya
```

Considering that the main intent of Publish is to run it in foreign interpreters, I'm weary about going too rouge on this. What do you think?

**Comment by ColinDuquesnoy** [comment]
Yes namespace packages are a sort of hack in python 2 and won't work if setuptools or pkgutil cannot be found (depending on how you declare your namespace package).

You will have to experiment. 

I would start with the entire setuptools package in a zip archive that is added to sys.path by your main package (of course you have to make sure to make the sys.path modification before importing (or declaring) any namespace packages)

I would also try to declare namespace packages using pkgutils instead of setuptools and see if it works better in maya and other environments.

``` python
from pkgutil import extend_path
__path__ = extend_path(__path__, __name__)
```

**Comment by mottosso** [comment]
Allright, thanks a bunch Colin!

**Comment by mottosso** [comment]
Going with regular packages for now, feel free to re-open if anyone has got anything to add.
