### ISSUE TITLE
Extraction plugins are solely responsible for placing files

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-base#59]
This is very powerful, but won't do much good if each plugin stores data in different locations.

What would be better, is if the baseclass for Extraction could provide a mechanism with which to finally place file on disk where they belong, so that a Conform plugin could take it from there.

``` python
# Currently
class MyExtractor(Extractor):
     def process(self, context):
         # Produce file in a temp directory
         files = ['file1', 'file2']
         # Move files to extraction destination
         shutil.copy('/my/unique/directory')

# Ideally
class MyExtractor(Extractor):
     def process(self, context):
         # Produce file in a temp directory
         files = ['file1', 'file2']
         # Move files to extraction destination
         self.commit(files)
```

**Comment by tokejepsen** [comment]
I was wondering about this the other day, as I wanted to look into making a Conformer. Won't the context need this information, for the Conformer to pick up down the line?

**Comment by mottosso** [comment]
For plugins to accurately place files relative the working file, it must somehow have access to where the working file is located.

The end result is documented here:
- https://github.com/abstractfactory/pyblish/wiki/Extraction

One method could be to pass this information into the context when it is first being created.

``` python
def publish_all():
    current_path = cmds.workspace(dir=True, query=True)
    context  = pyblish.backend.plugin.Context(current_path=current_path)
```

A plugin could then use the information.

``` python
class MyExtractor(Extractor):
     def process(self, context):
         final_path = os.path.join(context.current_path, 'published')
```

It does however mean a dependency between `publish_all()` and Maya, in which case we'll need a Maya-specific implementation of it.

``` python
pyblish_maya.main.publish_all()
```

> I was wondering about this the other day, as I wanted to look into making a Conformer. Won't the context need this information, for the Conformer to pick up down the line?

Yes, it most certainly does. We'll have to find a good way to distribute this information, without getting tangled.

**Comment by mottosso** [comment]
It struck me that this isn't an isolated requirement. Conform will also need a bunch of information, e.g. the source-file from which an instance was published, for reference to other users.

So, how about making the "additional data" gathering part of the Selection process? A selector could gather information about the scene, such as the workspace and file-name and such.

A pair of default selectors could gather the global information such as time of publish, currently logged on user and other data.

In the end, the context would have access to this information and if at any point in time a user makes more plugins that depends on further information, they could just make another selector to gather it up.

Our current selector merely finds instances and their configuration, but I think it makes sense for them to also operate on the context itself. Especially now that we're passing the entire context to each selector!

**Comment by tokejepsen** [comment]
I still dont quite get where the Conformers are going to get the information about f.eks. the files produced by the Extractors, if the Extractors aren't adding data to the context?

**Comment by mottosso** [comment]
I'll try and explain.

### How information flows

``` python

1.           |  2.                   |  3.                  |  4.
The context  |  Selector uses cont-  |  Extractor uses in-  |  Conform uses path   |  
is empty.    |  ext and appends in-  |  stance and appends  |  and moves it to its |  
             |  stance.              |  path of files.      |  final destination.  |  
             |                       |                      |                      |  
             |   __________________  |   _____________      |   _________________  |  
             |  |                  | |  |             |     |  |                 | |  
   Start ------>| SelectObjectSets |--->| ExtractAsMa |------->| ConformToServer |---->
             |  |__________________| |  |_____________|     |  |_________________| |  
             |                       |                      |                      |   
 _________   |   _________           |   _________          |   _________          |  
|         |  |  |         |          |  |         |         |  |         |         |  
| Context |  |  | Context |          |  | Context |         |  | Context |         |  
|_________|  |  | ________|_______   |  | ________|_______  |  | ________|_______  |  
             |  || instance       |  |  || instance       | |  || instance       | |  
             |  ||________________|  |  ||  .path         | |  ||  .path         | |  
             |  |_________|          |  ||________________| |  ||________________| |  
             |                       |  |_________|         |  |_________|         |  
             |                       |                      |                      |  
```

In this example, we start out with the context, it's empty. No nodes nor attributes. 

The selector then appends existing instances in the scene to the context, along with any attributes it can find; in this case the user-defined attributes on the objectSets, like `family` and `publishable`.

Then, the extraction exports files to a temporary location relative the working file and appends the resulting path to each instance, or context. Not sure yet. But this is where the information is inserted into the process.

> The temporary location `path` is something like `/maya/published/20140804-2105/MyAsset.mb`

Finally, the conform will get a hold of the context along with any attributes passed into it previously, including the temporary path. It can use this path to position it.

### How the extractor can know about the current working file

Currently, the extractor gathers information about the file directly from the `cmds.workspace()` command. But because of this, we can't assume to know about it in the base-class and thus not provide a common `commit()` method that places it in the common, temporary location.

So, the information could be "selected", similar to how nodes are selected in the scene.

``` python

1.           |  2.                   |  3.                     |  4.
The context  |  Selector looks at    |  Maya-specific - appe-  |  Extractor uses the  |  
is empty.    |  the environment and  |  nds the current work-  |  working file to f-  |  
             |  inserts the curren-  |  ing file.              |  igure out where to  |  
             |  tly logged on user.  |                         |  temporarily store.  |  
             |   __________________  |   ___________________   |   _________________  |  
             |  |                  | |  |                   |  |  |                 | |  
   Start ------>| SelectUser       |--->| SelectCurrentFile |---->| ExtractAsMa     |---->
             |  |__________________| |  |___________________|  |  |_________________| |  
             |                       |                         |                      |   
 _________   |   _________           |   _________             |   _________          |  
|         |  |  |         |          |  |         |            |  |         |         |  
| Context |  |  | Context |          |  | Context |            |  | Context |         |  
|_________|  |  | ________|_______   |  | ________|_______     |  | ________|_______  |  
             |  || instance       |  |  || instance       |    |  || instance       | |  
             |  ||  .user         |  |  ||  .user         |    |  ||  .user         | |  
             |  ||________________|  |  ||  .currentfile  |    |  ||  .currentfile  | |  
             |  |_________|          |  ||________________|    |  ||________________| |  
             |                       |  |_________|            |  |_________|         |  
             |                       |                         |                      |  
```

In our node-graph workflow, this is simply chaining one selector after another, and things work the same way here. Each selector will append to the context. It can either append instances, or attributes.

In this way, we can provide a bunch of included selector that gathers information about the system in general, information that we could then assume to know in our included validators, extractors and conformers.

Users could append additional selectors and gather even more data, such as data specific for Maya in this case, that they could assume to know in their conforms.

Part of what we provide per default for Maya could in fact be these general selectors, appending scene file, workspace etc. These are things users could implement themselves, but if we want to use the information in our other included plugins, there is no harm in including them ourselves.

The end result is, no black boxes and "eating our own dogfood" in a way, as our own implementations are the same as custom implementations by users. Its all plugins.

Does it make any more sense than before?

**Comment by tokejepsen** [comment]
> In our node-graph workflow, this is simply chaining one selector after another, and things work the same way here. Each selector will append to the context. It can either append instances, or attributes.

I like it! Makes for more flexible code and reuse.

**Comment by mottosso** [comment]
Me and @ljkart spoke about this and came up with something that extends upon this to make it even cooler. (I'm talking about the individual GUI's per-plugin, Liju). That will make for a good post in our Google Group. ;)
- https://groups.google.com/forum/#!forum/pyblish

**Comment by mottosso** [comment]
Configurable plugins, posted here
- https://groups.google.com/forum/#!topic/pyblish/s0oXnr3ApZ8
