### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-base#6]
Currently under the LGPL, although this may prevent studios from fully adapting it to their needs. Is MIT better suited?

**Comment by mottosso** [comment]
Actually, LGPL would keep efforts focused and better ensure the survival of Publish. It'd still be free and open, but any efforts made by individual studios would end up in this project, of forks, which would all be compatible with each other. MIT would introduce incompatible alternatives.

**Comment by achayan** [comment]
MIT or Apache will be best for our project I think and we really don't have any patent issues.

**Comment by mottosso** [comment]
Thanks for your input, Kurian.

To provide some perspective for those who aren't familiar with the types of licenses out there and what they mean, head here:
- http://choosealicense.com/

And for an interesting discussion on "Why GPL instead of BSD/MIT-style licenses?", head here:
- http://zguide.zeromq.org/py:all#The-Importance-of-Contracts

My main interest lies in the prosperity of this project. Whatever license that can best preserve this is the one I'd go for and although MIT means _"do anything you want"_, it also means _"take this, sell it, and don't contribute anything back"_ which may hurt us developers; essentially providing resources to a third-party for free, whether we wanted to or not. GPL on the other hand means _"take this, use it, your modifications belong to all of us."_ whereas the "L" in front of it means _"take this, bundle it together with another project as closed source, but be sure to provide access to any modifications you do"_

**Comment by mottosso** [comment]
Another increasingly important aspect of licensing is how we choose to license our Wiki/Documentation. To get the ball rolling, how about this?

http://creativecommons.org/licenses/by-sa/4.0/

In a nutshell, it means people are free to distribute variations, as long as it falls under the same license, and that it's also free for use in commercial environments, such as our workplaces.

There are a few variations here:

http://creativecommons.org/choose/

**Comment by mottosso** [comment]
I'm tempted to close this and move on, but before I do, @achayan, would it be possible for you to double-check whether LGPL would make it difficult for your studio to use Publish?

The code we've written so far automatically falls under LGPL - due to it being the current license - and though switching shouldn't pose a problem - as long as we're all in consensus about it - it's better to do it now rather than later.

As far as I can tell, LGPL shouldn't hinder anyone from using it. PySide is LGPL, for instance.

**Comment by achayan** [comment]
@mottosso I think we are really good to go with LGPL. I didn't see any kind of difficulty will be there for studios to take publish to their pipeline. We will be good with LGPL. Unless we file any kind of patents which I think we are not going to do right?.

**Comment by mottosso** [comment]
> Unless we file any kind of patents which I think we are not going to do right?.

I'm not sure, but I don't think we can file any patents regardless, as I think for a patent to come through, the technology will have to have been kept a secret.

> By far the most common mistake made by people new to the world of patents is to reveal their invention too early.
> - http://www.ipo.gov.uk/p-apply.pdf

Is this what you meant?

**Comment by mottosso** [comment]
Considering this matter solved!
