### ISSUE TITLE
Creating a separated menu for pyblish

### ISSUE THREAD

**Issue by ljkart** [pyblish/pyblish-base#60]
How about having a separated menu for pyblish rather messing up with the File Menu, which help us to put all pyblish related tools in a separated section, easy to find and optimize.
thoughts?

**Comment by mottosso** [comment]
This is my personal opinion, but I think that anything that integrates with something else should make an effort to conform with how built-in functionality works. In this case, everything that deals with files in Maya is located in its file-menu.

Alembic however doesn't follow this and adds a separate menu, making exporting as alembic feel like an isolated feature, less compatible with the overall workflow of Maya.

But it's a good point, this should be an option. How about providing multiple integration options, one for adding to the file-menu, and another that adds a separate menu. This could be in the form of two `userSetup.py`. E.g.
- [ ] ![dir](https://cloud.githubusercontent.com/assets/2152766/4041935/76446912-2cfd-11e4-8f04-df5e00e861ff.png) pyblish_maya
  - [ ] ![dir](https://cloud.githubusercontent.com/assets/2152766/4041935/76446912-2cfd-11e4-8f04-df5e00e861ff.png) pythonpath
    - [ ] ![dir](https://cloud.githubusercontent.com/assets/2152766/4041935/76446912-2cfd-11e4-8f04-df5e00e861ff.png) add_to_filemenu
      - [ ] ![file](https://cloud.githubusercontent.com/assets/2152766/4041938/82aabf1c-2cfd-11e4-8625-490f55adccab.png) userSetup.py
    - [ ] ![dir](https://cloud.githubusercontent.com/assets/2152766/4041935/76446912-2cfd-11e4-8f04-df5e00e861ff.png) add_to_new_menu
      - [ ] ![file](https://cloud.githubusercontent.com/assets/2152766/4041938/82aabf1c-2cfd-11e4-8625-490f55adccab.png) userSetup.py

If you add `add_to_new_menu` to your PYTHONPATH, you will get it as a separate menu. That way, users can choose which they prefer.

In the future, we could provide this as an option to the Maya-installer of the integration.

**Comment by mottosso** [comment]
If you have anything more to add, @ljkart feel free to re-open this issue.
