### ISSUE TITLE
Testing individual plugins

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-base#61]
So I was trying to troubleshoot a plugin, and couldn't find a way to isolate the plugin.

``` python
import pyblish
import pyblish.backend.plugin
import pyblish_maya.plugins.extract_review
reload(pyblish_maya.plugins.extract_review)

cxt = pyblish.backend.plugin.Context()

for instance, error in pyblish.main.select(cxt):
    print "Selected {0}".format(instance)

review = pyblish_maya.plugins.extract_review.ExtractReviewAsPng()
review.process(cxt)
```

Nothing happens when running this code.

**Comment by mottosso** [comment]
Yes, this is a bit confusing, but it has to do with the "generator" workflow discussed here: #54 

In a nutshell, when you run `review.process(ctx)` you're just creating a generator, but you need to run it too. You can run it by either putting it in a for-loop:

``` python
for instance, error in review.process(ctx):
    pass
```

Or using `next()`

``` python
instance, error = next(review.process(ctx))
```

We'll have to work on making this more obvious.

But, as for running individual plugins, the way you've done it works. Another way is to use the `discover()` function of `plugin.py`.

``` python
import pyblish.backend.plugin
review = pyblish.backend.plugin.discover(type='extractors', regex='ExtractReviewAsPng')
instance, error = next(review.process(ctx)
```

See the tests for more examples.
https://github.com/abstractfactory/pyblish/blob/master/pyblish/backend/tests/test_plugins.py#L82

**Comment by tokejepsen** [comment]
> But, as for running individual plugins, the way you've done it works

Maybe I'm doing something wrong on my end, but the code I posted does not run the plugin. Nothing gets playblasted.

``` python
import pyblish.backend.plugin
review = pyblish.backend.plugin.discover(type='extractors', regex='ExtractReviewAsPng')
instance, error = next(review.process(ctx)
```

This certainly seems easier to get the plugin, but does that also reload it for quicker iterations?

**Comment by mottosso** [comment]
> This certainly seems easier to get the plugin, but does that also reload it for quicker iterations?

It does, or rather, it never gets cached and thus gets reimported each time. That's the `imp` module at work.

> Maybe I'm doing something wrong on my end, but the code I posted does not run the plugin. Nothing gets playblasted.

Maybe try it out on a more minimal plugin, and print things to see what's going on. The tests will have many examples like this, with mocked up Context and Instances. Do have a look at those.

**Comment by mottosso** [comment]
I think this issue is answered here:
http://pyblish.com/#mocking-with-pyblish
