### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-base#63]
Hi everyone,

I've sketched out how I envision our roadmap from where we are today, the end of August, up till our first 1.0 release.

![roadmap1](https://cloud.githubusercontent.com/assets/2152766/4090024/3681672c-2f77-11e4-8a83-38c32b82bdbe.png)

As you can see, we've started out small with small ambitions and have grown to envision Pyblish being a really useful tool in lots of situations for a lot of different people. We've begun work on multiple areas at once, so that you can all contribute with your interests and expertise without having to change too much of the main functionality. This means development will be able to accelerate, slowly but surely.
### 1.0

We're also getting close to a release usable by others. Now, I know this is a little scary and may feel premature. Committing to a 1.0  means that we will have to stand by and support our mistakes and awkward implementations and workflows.

However, everything we learn from the 1.0 will be directly applicable to a 2.0, and a 2.0 doesn't have to be backwards compatible with the 1.0, thus allowing us to scrap old code in favour of new code.

The critical point of a 1.0 is to get something into people's hands. Something they can confidently develop with, without feeling like their plugins will break with the next point release (e.g. 1.1). Only when we can get it into peoples hand and into actual productions will we be able to draw estimates on where to go next, what to improve and what to leave as-is.
### It's only a sketch

Yes, take it with a grain of salt. It will most likely change a lot, and that's a good thing. It means our understanding of the project and its goals have increased. One of the thing that may change a lot is our node-based workflow, and that's completely fine. At no point should we stop dreaming and coming up with awesome ideas. If the idea doesn't fit the next release, we'll keep it for the next. And that's how it'll go.
### Google Groups

In addition, this will be the last "discussion" I'll be posting in the issues section of GitHub. I'd like to propose moving discussions into our brand new Google Groups, located here:
- https://groups.google.com/forum/#!forum/pyblish

And keep issues about issues that can be fixed. If you have something to add, ask yourself "can this be fixed by a pull-request?" If the answer is "Yes", then it's an issue. Otherwise, it's a discussion and belongs in the Google Group.
### Anything left out?

If you find something missing from the Roadmap above, do speak up and we'll talk about including it in the 1.0.

Best,
Marcus

**Comment by ljkart** [comment]
Excellent! we are on right track...!

**Comment by mottosso** [comment]
# Alpha

Hi Team,

I'm just about to make an announcement about the alpha release of Pyblish 1.0. Take a moment to read through what will become their first impression here:

### [pyblish.com](http://pyblish.com)

You can install Pyblish 1.0 alpha via pip, like this:

``` bash
$ pip install pyblish
$ python
>>> import pyblish
>>> pyblish.version
'1.0.0'
```

Look for errors, ambiguities and room for improvement. This page should convince non-believers, enlight those who do not know of publishing and encourage widespread use of our work, Pyblish, the plug-in driven automation framework for content.

# Goal

The goal of this release is to attract users. We'll do this by providing a guide, like the one above, an interface capable of most things and a few examples to confirm that all is working well. I'll be posting on various forums:
- python-inside-maya
- Tech-artists.org
- Gamedev.org
- CGTalk
- CGChannel

If you can think of more channels with potential users, speak up here. Ideally, we'll start with the least amount of users and work our way up, so as to discover early problems with as small of an audience as possible.

# The future

We still haven't got a UI to speak of, and that should most certainly be part of the 1.0. This is merely an Alpha, meaning things will change, but not as drastically as before. By the end of the Alpha, the idea is to have found a method of developing plugins, configuring them and exposing them to various parts of a pipeline that is both powerful, intuitive and comfortable to work with.

I think we are getting close to that now.

### Beta

The next step is Beta, which means only bug-fixes are allowed to change any existing behaviour, but that we can still add features.

### RC

Finally, we will fade out with RC, release candidates, which will stay out in the wild for a few weeks on trial until finally reaching our 1.0 final.

### Final

From there, we're entering the standard software cycle of new features and improvements. This is where the fun really begins!

# Now

From here, we'll keep spawning ideas and making improvements. If you should find a scenario in which the current implementation fails to deliver, now is the time to speak up, because once the Alpha is over, we'll get to work on the fun stuff; developing awesome libraries of plugins that provide real value to our users. To do that we'll need a fixed ground to stand on, any major modifications will have to wait for a 2.0 release.

**Comment by mottosso** [comment]
Announced here:
- http://tech-artists.org/forum/showthread.php?4973-Pyblish-1-0-Alpha
- https://groups.google.com/forum/#!topic/python_inside_maya/KF2wYEdqe5g

**Comment by mottosso** [comment]
The future is now!
