### ISSUE TITLE
Filter -> Plugin

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-base#64]
I think it makes more sense to call our current superclass [`Filter`](https://github.com/abstractfactory/pyblish/blob/1166405cd08863165832072f677564f1a3876642/pyblish/backend/plugin.py#L55) for `Plugin`, as it is a superclass for all of our plugins. We can reserve the terminology for the "[pipes and filters](http://msdn.microsoft.com/en-us/library/ff647419.aspx)" implementation we'll use for the node-workflow.

Any objections?

**Comment by tokejepsen** [comment]
+1
