### ISSUE TITLE
Plugins within identical file-names are duplicated

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-base#67]
When importing plugins from a module `select_environment.py` located within one directory and another file of identical name within another directory the contents of said module is appended to rather than replaced.

I've narrowed it down to a caveat within the `imp` module which is used for dynamic loading of Python modules.

``` python
>>> mod1 = imp.load_source(name='select_environment', 
                           pathname='c:\some\path\select_environment.py')
>>> id(mod1)
55555551
>>> dir(mod1)
UniqueClass1
UniqueClass2
>>> mod2 = imp.load_source(name='select_something_else', 
                           pathname='c:\some\path\select_something_else.py')
>>> id(mod2)
55555552
>>> dir(mod2)
UniqueClass3
```

This is what we would expect, the two modules take up separate portions of memory and are thus completely separate objects. Loading one does not have any affect on the other; i.e. there are no side-effects.

``` python
>>> mod1 = imp.load_source(name='select_environment', 
                           pathname='c:\some\path\select_environment.py')
>>> id(mod1)
55555551
>>> mod2 = imp.load_source(name='select_environment', 
                           pathname='c:\some\other\path\select_environment.py')
>>> id(mod2)
55555551
```

> Note the difference in its `pathname`, but identical `name`.

Here on the other hand, memory locations are identical, suggesting that `imp` has replaced `mod1` with `mod2`. What really happens however is a merge.

``` python
>>> mod1 = imp.load_source(name='select_environment', 
                           pathname='c:\some\path\select_environment.py')
>>> dir(mod1)
UniqueClass1
UniqueClass2
>>> mod2 = imp.load_source(name='select_environment', 
                           pathname='c:\some\other\path\select_environment.py')
>>> dir(mod2)
UniqueClass1
UniqueClass2
UniqueClass3
```

> Note that `UniqueClass1` and `UniqueClass2` is present in both `mod1` and `mod2`

This caused plugins to accumulate and cause lots of duplicated plugins to be processed whenever they were sharing names.

**Comment by tokejepsen** [comment]
Wow, thats quite a bit of detective work there:) Have you got a fix in mind?

**Comment by mottosso** [comment]
Heh, yeah thought I was going mad. :) I'm working on it, but at the moment it seems the simplest way to go is to ensure unique names of modules, which seems to be working fine so far.

The reason we haven't caught it until now is because we've never checked for duplicate plugins before. We haven't had that many so it hasn't been noticeable.

**Comment by mottosso** [comment]
The proposed solution looked like this, which worked initially. But has a serious flaw, can you spot it?

``` python
try:
    # Create a local copy of sys.path, clear it
    # and add our plugin path to try and import.
    # Once done, restore sys.path.
    sys_path = list(sys.path)
    sys.path[:] = []

    sys.path.append(path)
    module = importlib.import_module(mod_name)

except (ImportError, IndentationError) as e:
    log.warning('"{mod}": Skipped ({msg})'.format(
        mod=mod_name, msg=e))
    continue

finally:
    # Restore sys.path
    sys.path[:] = sys_path
```

> Hint: It hides other potential targets for plugins, which is what we want, but it also hides site-packages and thus all built-in modules.
