### ISSUE TITLE
validate_naming_convention: regex pattern configuration

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-base#77]
Just an idea I had, that the regex pattern for the [validate_naming_convention](https://github.com/abstractfactory/pyblish/blob/master/pyblish/plugins/validate_naming_convention.py) could be configurable.

I know we dont have configuration for the plugins yet, but this is a use case for that.

**Comment by mottosso** [comment]
That's a good idea. It would make it a little more official. However, it's family will still be singular or at least fixed, which means users might have to subclass it regardless.

If we solve that, we could add it to the default Pyblish configuration, and let users configure it like this:
http://pyblish.com/#configuring-pyblish

Our convention could be to provide configuration options for the plugins we ship with Pyblish. That should keep configuration interesting and also concise. At the moment, we're already using it for a Maya plugin, select_object_set, in which we're using the identifier.

**Comment by mottosso** [comment]
I think this is has landed outside the scope of Pyblish, and more in the realm of implementing plug-ins that can be configured individually, potentially with their own GUI or configuration files.
