### ISSUE TITLE
Nice name property for plugins

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-base#84]
In preparation for the ui, we need a nice name property on all plugins.

So instead of seeing "extract_alembic", the user would see "Extract Alembic".

We could possibly have some description information as well... somehow?

**Comment by mottosso** [comment]
Plugins aren't actually named by the module they are in (there can actually be multiple plugins in a single module, although it hasn't been documented yet).

I've always imagined names coming from their class name, e.g. "ExtractAsAlembic", which can be parsed into putting spaces inbetween each upper-case letter, similar to how Maya deals with attribute names versus nice-names.

But having an attribute to override this is a good idea.

How about this:

``` python
class ExtractAlembic(Extractor);
     families = ['demo.anim']
     name = 'My Awesome Plugin!"
```

If it doesn't have a `name` attribute, the class-name is used.

**Comment by mottosso** [comment]
I'd put description there as well.

``` python
class ExtractAlembic(Extractor);
     families = ['demo.anim']
     name = 'My Awesome Plugin!"
     description = 'This plugin does awesome things!'
```

**Comment by tokejepsen** [comment]
Sounds good to me:)
