### ISSUE TITLE
Lack of consistency of values returned when checking custom paths

### ISSUE THREAD

**Issue by ghost** [pyblish/pyblish-base#85]
Would it be possible to get `pyblish.backend.config.paths` and `pyblish.backend.plugin.plugin_paths()` to return processed paths? At the moment, only the second one does.

``` python
>>> pyblish.backend.config.paths
['{pyblish}/plugins', 'c:/myPlugins']
```

``` python
>>> pyblish.backend.plugin.plugin_paths()
['c:/python27/lib/site-packages/pyblish/plugins', 'c:/myPlugins']
```

**Comment by mottosso** [comment]
Thanks for reporting this, David.

One solution, off the top of me head, is to make a dedicated function to visualise configured paths.

``` python
>>> pyblish.backend.plugin.configured_paths()
['c:/python27/lib/site-packages/pyblish/plugins', 'c:/myPlugins']
```

Along with one for environment and registered paths, for consistency.

``` python
>>> pyblish.backend.plugin.environment_paths()
['c:\my_environment_path']
>>> pyblish.backend.plugin.registered_paths()
['c:\my_registered_path']
```

As `config` is meant as an interface to the file itself, I'd rather not have it do any processing and actually expand that variable on its own. Especially considering that it may be useful to see what the actual variables are, as well as being able to add to the config via Python.

``` python
>>> pyblish.backend.config.paths = ['{my_variable}/plugins']
```

**Comment by mottosso** [comment]
@davidmartinezanim I've added the methods above, they're also accessible via the new API.

``` python
import pyblish
pyblish.registered_paths()
pyblish.environment_paths()
pyblish.configured_paths()
```
