### ISSUE TITLE
Renaming Instance

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-base#86]
One of the things I tend to explain often is what an _Instance_ is, on the outset that it is something that is being used multiple times given an original source, like a Maya instance.

The bottom line is, what is generally referred to as an instance aligns quite well with how we use it; as an _instantiation_ of content, such as a file. A Maya Instance is just that, a "reference" to an original, something that mirrors it.

Despite this however, I have gotten two reports of it being confusing, and I expect more to come in.
### Definition

Before we can try out new terms, let's first properly define it.

**Instances** are meant to be an in-memory representation of content from disk, such as a rig coming in from `my_rig.mb`. Once the file has been loaded, it has become a **Instance**.

The same is true for outgoing data. Upon creating new content, one must first create a **Instance** that will, once published, become content; i.e. files on disk.
1. An **Instance** is an _instantiation_ of content, such as a file.
2. An **Instance** is a collection of selected data.

Thus, we need a term that can be used both for content coming into hosts and for defining content going out of hosts.
### Alternatives
- Asset
- Bundle
- Package
- Resource
- Selection
### `Asset`

This could be a good name, however it may confuse users with the resulting files on disk. Is the file the asset, or the data in your scene prior to getting published? It's also very likely already used in more established pipelines, and it can be useful to be able to reference a thing as being either an in-memory representation of content or content persisted on disk.

``` python
from pyblish.backend import plugin
context = plugin.Context()
asset = context.create_asset(name='MyAsset01')
```
### `Bundle`

The motivation being that it is a collection of items and data. It does however sound rather similar to the definition of Context, which is a collection of Instances.

``` python
from pyblish.backend import plugin
context = plugin.Context()
bundle = context.create_bundle(name='MyBundle01')
```
### `Package`

Like `Bundle`, it does sound rather similar to Context's definition, along with occupying the same name as a Python Package.

``` python
from pyblish.backend import plugin
context = plugin.Context()
package = context.create_package(name='MyPackage01')
```
### `Resource`

A general term, normally given to web resources, as "any data accessible via a URL". It doesn't speak much for what it is however, a collection of selected data to be published.

``` python
from pyblish.backend import plugin
context = plugin.Context()
resource = context.create_resource(name='MyResource01')
```
### `Selection`

Though dangerously close to sounding like a selection plugin, a `Selection` may be a rather good description, as data collected by the selector plugins have, in a sense, become _selected_. However _selection_ makes less sense for content coming into a host. Like when loading a rig, the rig has become a _Selection_.

It may also confuse users to think that it has something to do with what is currently selected in the scene.

``` python
from pyblish.backend import plugin
context = plugin.Context()
selection = context.create_selection(name='MyAsset01')
selection = cmds.ls(selection=True)
```

**Comment by tokejepsen** [comment]
if we are looking to change instance, we should probably look at changing
Context as well. Where I do like bundle.

I’m leaning towards asset since its quite familiar to people can be a lot
of things. Although I do share the concerns about the confusion with files
on disk.

Throwing some suggestions out there:

_Instance_
- chunk
- unit
- cargo
- pack
- crate
- packet
- item

_Context_
- container
- collection

​

**Comment by mottosso** [comment]
> if we are looking to change instance, we should probably look at changing Context as well. Where I do like bundle.

Let's stick with one renaming per issue.

> I’m leaning towards asset since its quite familiar to people can be a lot of things. Although I do share the concerns about the confusion with files on disk.

The familiarity can be both a blessing and a curse. By using something familiar, we are expected to conform to an already established notion of what it is. Unfortunately with the term `asset`, very few share the same notion - is as rig an asset? a playblast? a task? - which ultimately leads us to the same question we're at now - "what is an instance?"

Ideally, the new terminology should occupy no notion so as to start from as a blank slate as possible. From there, we can pain our own canvas, so to speak.

We could consider using new words.
- Soc (Selected Objects Container), pronounced "sock"
- PCR (Persisted Content Representation), pronounced "pee-sar"
- datac (Data Container), pronounced "date-ack"

# Suggestions

As you didn't describe the motivation to your suggestions, I'll fill in with my thoughts. The two most important thing about the new term is:
1. That it is easy to remember and to write
2. That it doesn't get confused with something else

### `Chunk`

``` python
context = pyblish.backend.plugin.Context()
chunk = context.create_chunk(name='MyChunk')
```

Although no particular notion attached, it does suggest that a chunk is only part of something whole, something separated that belong together/came from somewhere bigger.

### `Unit`

This is good. To me it represents a whole, something capable of fending for itself, yet still be part of something bigger.

In terms of describing its origin and relation to files on disk however, I'm having trouble seeing as clear of a link as with instance, which can be described as "an instantiation of content". If we can't give it a clear origin, it fails on point 1 above.

### `Cargo`, `Pack`, `Crate`

These are much too focused on being a collection of things, as opposed to something to be extended upon or used on its own, like a model is to a rig is to an animation.

### `Packet`

This is good. I can't think of how it would interfere with other notions and I could imagine it being extended or used on its own. It does however fail point 1 unless we can give it a reason for being called a packet.

### `Item`

This is too heavily used in GUIs as items within a list or tree. Typically associated with a graphical representation of a non-graphical object.

# Finally

To be honest, I still believe that `Instance` fulfils its responsibilities. Though it does share notion with Maya Instances or Instances in Rendering, it doesn't share usage space; i.e. they are rarely if ever used together in a single sentence. In the same way we can use the term `family` and not confuse it with out own families, because it is out of context of the conversation.

### On trial

We could try and turn the table around and put `Instance` on trial to find out why it _isn't_ fit for service.

Here are some tests that it will need to pass.
1. _"Hey, can you publish those instances?",_ says the supervisor, pointing to your screen.
2. _"Something is wrong with the instancing",_ says artist about crowd simulation.
3. _"This rig came from an instance in *shot5_v001_marcus.mb_"*
4. _"Have you instanced the mesh?",_ says artist about leafs on a tree
5. _"Is this an instance?"_, says artist about a piece of geometry within Maya.

Here is a possible worst case scenario in Python.

``` python
context = pyblish.backend.plugin.Context()
instance = context.create_instance(name='MyInstance')
instances = cmds.ls(type='instance')  # Psuedo-code
for inst in instances:
    instance.add(inst)
```

Potentially remedied like this:

``` python
context = pyblish.backend.plugin.Context()
jack = context.create_instance(name='Jack')
for maya_instance in cmds.ls(type='instance'):
    jack.add(maya_instance)
```

**Comment by mottosso** [comment]
Considering this matter ended.
